CREATE TABLE IF NOT EXISTS creator_courses (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 owner_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(180) NOT NULL,
 description TEXT NOT NULL,
 price BIGINT UNSIGNED NOT NULL DEFAULT 0,
 status VARCHAR(20) NOT NULL DEFAULT 'draft',
 cover_id BIGINT UNSIGNED NULL,
 curriculum LONGTEXT NOT NULL,
 version INT UNSIGNED NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX (owner_id), INDEX (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS creator_course_media (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 course_id BIGINT UNSIGNED NOT NULL,
 filename VARCHAR(80) NOT NULL,
 mime VARCHAR(80) NOT NULL,
 bytes BIGINT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (course_id) REFERENCES creator_courses(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS creator_course_orders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 course_id BIGINT UNSIGNED NOT NULL,
 buyer_id BIGINT UNSIGNED NOT NULL,
 seller_id BIGINT UNSIGNED NOT NULL,
 amount BIGINT UNSIGNED NOT NULL,
 currency VARCHAR(3) NOT NULL DEFAULT 'IRT',
 status VARCHAR(20) NOT NULL DEFAULT 'created',
 token CHAR(64) NOT NULL UNIQUE,
 authority VARCHAR(100) NULL UNIQUE,
 reference_id VARCHAR(100) NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 paid_at DATETIME NULL,
 FOREIGN KEY (course_id) REFERENCES creator_courses(id),
 INDEX (buyer_id, course_id, status), INDEX (seller_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS creator_course_lessons (
 post_id INT UNSIGNED PRIMARY KEY, course_id BIGINT UNSIGNED NOT NULL,
 media_json TEXT NOT NULL, requires_password TINYINT NOT NULL DEFAULT 0,
 password_revision INT UNSIGNED NOT NULL DEFAULT 1, deleted_at DATETIME NULL,
 FOREIGN KEY(post_id) REFERENCES posts(post_id),
 FOREIGN KEY(course_id) REFERENCES creator_courses(id), INDEX(course_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS creator_lesson_access (
 user_id BIGINT UNSIGNED NOT NULL, post_id INT UNSIGNED NOT NULL,
 password_revision INT UNSIGNED NOT NULL, PRIMARY KEY(user_id,post_id),
 FOREIGN KEY(post_id) REFERENCES posts(post_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
