CREATE TABLE IF NOT EXISTS social_story_mentions (
 story_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(story_id,user_id), FOREIGN KEY(story_id) REFERENCES social_posts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS social_highlights (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, owner_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(80) NOT NULL, cover_id BIGINT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(owner_id), FOREIGN KEY(cover_id) REFERENCES social_media(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS social_highlight_stories (
 highlight_id BIGINT UNSIGNED NOT NULL, story_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(highlight_id,story_id), INDEX(story_id),
 FOREIGN KEY(highlight_id) REFERENCES social_highlights(id) ON DELETE CASCADE,
 FOREIGN KEY(story_id) REFERENCES social_posts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
