-- Explicit schema step run by the reviewed CLI migration, never an HTTP request.
ALTER TABLE f_financial_system_payments
 MODIFY amount DECIMAL(22,2) NULL,
 MODIFY method VARCHAR(30) NULL,
 MODIFY status VARCHAR(30) NULL,
 ADD record_type VARCHAR(30) NOT NULL DEFAULT 'legacy',
 ADD source_table VARCHAR(100) NULL,
 ADD source_id BIGINT UNSIGNED NULL,
 ADD installment_id BIGINT UNSIGNED NULL,
 ADD gateway VARCHAR(30) NULL,
 ADD payer_name VARCHAR(190) NULL,
 ADD bank_card_type VARCHAR(40) NULL,
 ADD currency VARCHAR(3) NULL,
 ADD callback_token CHAR(64) NULL,
 ADD authority VARCHAR(64) NULL,
 ADD reference_id VARCHAR(64) NULL,
 ADD card_pan VARCHAR(32) NULL,
 ADD card_hash VARCHAR(128) NULL,
 ADD gateway_code INT NULL,
 ADD gateway_message VARCHAR(500) NULL,
 ADD description VARCHAR(1000) NULL,
 ADD requested_at DATETIME NULL,
 ADD verified_at DATETIME NULL,
 ADD UNIQUE KEY uq_payment_source(source_table,source_id),
 ADD UNIQUE KEY uq_payment_callback(callback_token),
 ADD UNIQUE KEY uq_payment_authority(authority),
 ADD KEY idx_payment_invoice(record_type,invoice_id,status),
 ADD KEY idx_payment_installment(record_type,installment_id,status),
 ADD KEY idx_payment_receipts(record_type,status,deleted_at,paid_at);
