-- Comprehensive first-party behavioral analytics for Sornaz.
-- Apply once to the current MariaDB database.

ALTER TABLE `tracking_user_sessions`
  ADD COLUMN `visit_uuid` char(36) NOT NULL AFTER `tracking_user_session_id`,
  ADD COLUMN `authenticated_session_id` bigint(20) UNSIGNED DEFAULT NULL AFTER `session_id`,
  ADD COLUMN `status` enum('active','idle','ended','expired','abandoned') NOT NULL DEFAULT 'active' AFTER `guest_id`,
  ADD COLUMN `last_activity_at` datetime(3) DEFAULT NULL AFTER `started_at`,
  ADD COLUMN `last_heartbeat_at` datetime(3) DEFAULT NULL AFTER `last_activity_at`,
  ADD COLUMN `end_reason` enum('logout','tab_closed','browser_closed','timeout','session_expired','network_lost','unknown') DEFAULT NULL AFTER `ended_at`,
  ADD COLUMN `auth_revoked_at` datetime(3) DEFAULT NULL AFTER `end_reason`,
  ADD COLUMN `auth_revoked_by` bigint(20) UNSIGNED DEFAULT NULL AFTER `auth_revoked_at`,
  ADD COLUMN `active_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `idle_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `visible_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `hidden_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `events_count` int(10) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `engagement_score` decimal(8,4) DEFAULT NULL,
  ADD COLUMN `language` varchar(10) DEFAULT NULL,
  ADD COLUMN `timezone` varchar(64) DEFAULT NULL,
  ADD COLUMN `screen_width` smallint(5) UNSIGNED DEFAULT NULL,
  ADD COLUMN `screen_height` smallint(5) UNSIGNED DEFAULT NULL,
  ADD COLUMN `viewport_width` smallint(5) UNSIGNED DEFAULT NULL,
  ADD COLUMN `viewport_height` smallint(5) UNSIGNED DEFAULT NULL,
  ADD COLUMN `device_pixel_ratio` decimal(5,2) DEFAULT NULL,
  ADD COLUMN `platform` varchar(100) DEFAULT NULL,
  ADD COLUMN `app_version` varchar(50) DEFAULT NULL,
  ADD COLUMN `tracking_version` smallint(5) UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN `consent_status` enum('granted','denied','partial','unknown') NOT NULL DEFAULT 'unknown',
  ADD COLUMN `city_name` varchar(100) DEFAULT NULL,
  ADD COLUMN `region_name` varchar(100) DEFAULT NULL,
  MODIFY COLUMN `entry_page` varchar(1000) DEFAULT NULL,
  MODIFY COLUMN `exit_page` varchar(1000) DEFAULT NULL,
  ADD UNIQUE KEY `uq_tracking_visit_uuid` (`visit_uuid`),
  ADD KEY `idx_tracking_user_status_activity` (`status`,`last_activity_at`),
  ADD KEY `idx_tracking_user_user_started` (`user_id`,`started_at`),
  ADD KEY `idx_tracking_user_guest_started` (`guest_id`,`started_at`),
  ADD KEY `idx_tracking_user_auth_session` (`authenticated_session_id`);

ALTER TABLE `tracking_user_page_views`
  ADD COLUMN `page_view_uuid` char(36) NOT NULL AFTER `tracking_user_page_view_id`,
  ADD COLUMN `tab_id` varchar(64) DEFAULT NULL AFTER `tracking_user_session_id`,
  ADD COLUMN `sequence_number` int(10) UNSIGNED DEFAULT NULL AFTER `tab_id`,
  ADD COLUMN `page_path` varchar(1000) DEFAULT NULL AFTER `page_url`,
  ADD COLUMN `canonical_url` varchar(1000) DEFAULT NULL AFTER `page_path`,
  MODIFY COLUMN `page_type` varchar(50) DEFAULT NULL,
  ADD COLUMN `entity_type` varchar(50) DEFAULT NULL AFTER `page_type`,
  ADD COLUMN `entity_id` bigint(20) UNSIGNED DEFAULT NULL AFTER `entity_type`,
  ADD COLUMN `locale` varchar(10) DEFAULT NULL AFTER `entity_id`,
  ADD COLUMN `last_activity_at` datetime(3) DEFAULT NULL,
  ADD COLUMN `last_heartbeat_at` datetime(3) DEFAULT NULL,
  ADD COLUMN `total_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `visible_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `hidden_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `active_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `idle_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `reading_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `interaction_count` int(10) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `keypress_count` int(10) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `form_interaction_count` int(10) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `max_scroll_depth` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `max_scroll_y` int(10) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `content_height` int(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN `first_interaction_at` datetime(3) DEFAULT NULL,
  ADD COLUMN `last_interaction_at` datetime(3) DEFAULT NULL,
  ADD COLUMN `exit_reason` varchar(50) DEFAULT NULL,
  ADD COLUMN `is_completed` tinyint(1) NOT NULL DEFAULT 0,
  ADD UNIQUE KEY `uq_tracking_page_view_uuid` (`page_view_uuid`),
  ADD KEY `idx_tracking_page_session_sequence` (`tracking_user_session_id`,`sequence_number`),
  ADD KEY `idx_tracking_page_user_entered` (`user_id`,`entered_at`),
  ADD KEY `idx_tracking_page_entity` (`entity_type`,`entity_id`),
  ADD KEY `idx_tracking_page_type_entered` (`page_type`,`entered_at`);

ALTER TABLE `tracking_user_events`
  CHANGE COLUMN `tracking_user_eventsid` `tracking_user_event_id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN `event_uuid` char(36) NOT NULL AFTER `tracking_user_event_id`,
  ADD COLUMN `sequence_number` bigint(20) UNSIGNED NOT NULL AFTER `page_view_id`,
  ADD COLUMN `occurred_at` datetime(3) NOT NULL AFTER `event_label`,
  ADD COLUMN `received_at` datetime(3) NOT NULL DEFAULT current_timestamp(3) AFTER `occurred_at`,
  ADD COLUMN `client_timestamp_ms` bigint(20) UNSIGNED DEFAULT NULL AFTER `received_at`,
  ADD COLUMN `event_version` smallint(5) UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN `target_type` varchar(50) DEFAULT NULL,
  ADD COLUMN `target_id` varchar(191) DEFAULT NULL,
  ADD COLUMN `target_name` varchar(191) DEFAULT NULL,
  ADD COLUMN `target_text` varchar(255) DEFAULT NULL,
  ADD COLUMN `entity_type` varchar(50) DEFAULT NULL,
  ADD COLUMN `entity_id` bigint(20) UNSIGNED DEFAULT NULL,
  ADD COLUMN `section_key` varchar(100) DEFAULT NULL,
  ADD COLUMN `position_x` int(11) DEFAULT NULL,
  ADD COLUMN `position_y` int(11) DEFAULT NULL,
  ADD COLUMN `viewport_x` int(11) DEFAULT NULL,
  ADD COLUMN `viewport_y` int(11) DEFAULT NULL,
  ADD COLUMN `scroll_x` int(11) DEFAULT NULL,
  ADD COLUMN `scroll_y` int(11) DEFAULT NULL,
  ADD COLUMN `scroll_depth` smallint(5) UNSIGNED DEFAULT NULL,
  ADD COLUMN `duration_ms` int(10) UNSIGNED DEFAULT NULL,
  ADD COLUMN `numeric_value` decimal(18,4) DEFAULT NULL,
  ADD COLUMN `is_trusted` tinyint(1) DEFAULT NULL,
  ADD COLUMN `source` enum('client','server','system') NOT NULL DEFAULT 'client',
  ADD UNIQUE KEY `uq_tracking_event_uuid` (`event_uuid`),
  ADD KEY `idx_tracking_event_page_sequence` (`page_view_id`,`sequence_number`),
  ADD KEY `idx_tracking_event_user_time` (`user_id`,`occurred_at`),
  ADD KEY `idx_tracking_event_name_time` (`event_name`,`occurred_at`),
  ADD KEY `idx_tracking_event_entity` (`entity_type`,`entity_id`),
  ADD KEY `idx_tracking_event_section` (`section_key`,`occurred_at`);

CREATE TABLE `tracking_user_content_engagements` (
  `tracking_user_content_engagement_id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tracking_user_session_id` bigint(20) UNSIGNED NOT NULL,
  `page_view_id` bigint(20) UNSIGNED NOT NULL,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL,
  `section_key` varchar(100) NOT NULL,
  `section_type` varchar(50) DEFAULT NULL,
  `entity_type` varchar(50) DEFAULT NULL,
  `entity_id` bigint(20) UNSIGNED DEFAULT NULL,
  `impression_count` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `visible_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `active_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `idle_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `reading_duration_ms` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `max_visibility_percent` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
  `interaction_count` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `click_count` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `first_seen_at` datetime(3) DEFAULT NULL,
  `last_seen_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  `updated_at` datetime(3) DEFAULT NULL ON UPDATE current_timestamp(3),
  PRIMARY KEY (`tracking_user_content_engagement_id`),
  UNIQUE KEY `uq_tracking_page_section` (`page_view_id`,`section_key`),
  KEY `idx_tracking_engagement_entity` (`entity_type`,`entity_id`),
  KEY `idx_tracking_engagement_user` (`user_id`,`created_at`),
  KEY `idx_tracking_engagement_session` (`tracking_user_session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tracking_user_activity_intervals` (
  `tracking_user_activity_interval_id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `interval_uuid` char(36) NOT NULL,
  `tracking_user_session_id` bigint(20) UNSIGNED NOT NULL,
  `page_view_id` bigint(20) UNSIGNED DEFAULT NULL,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL,
  `activity_type` enum('active','idle','reading','hidden','disconnected') NOT NULL,
  `started_at` datetime(3) NOT NULL,
  `ended_at` datetime(3) DEFAULT NULL,
  `duration_ms` bigint(20) UNSIGNED DEFAULT NULL,
  `section_key` varchar(100) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  PRIMARY KEY (`tracking_user_activity_interval_id`),
  UNIQUE KEY `uq_tracking_activity_interval_uuid` (`interval_uuid`),
  KEY `idx_tracking_activity_session_time` (`tracking_user_session_id`,`started_at`),
  KEY `idx_tracking_activity_page_time` (`page_view_id`,`started_at`),
  KEY `idx_tracking_activity_user_type` (`user_id`,`activity_type`,`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tracking_ingestion_batches` (
  `tracking_ingestion_batch_id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `batch_uuid` char(36) NOT NULL,
  `tracking_user_session_id` bigint(20) UNSIGNED NOT NULL,
  `page_view_id` bigint(20) UNSIGNED NOT NULL,
  `events_count` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3),
  PRIMARY KEY (`tracking_ingestion_batch_id`),
  UNIQUE KEY `uq_tracking_ingestion_batch_uuid` (`batch_uuid`),
  KEY `idx_tracking_ingestion_session` (`tracking_user_session_id`,`created_at`),
  KEY `idx_tracking_ingestion_page` (`page_view_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `tracking_user_consents` (
  `tracking_user_consent_id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL,
  `guest_id` varchar(64) DEFAULT NULL,
  `analytics_allowed` tinyint(1) NOT NULL DEFAULT 1,
  `personalization_allowed` tinyint(1) NOT NULL DEFAULT 0,
  `marketing_allowed` tinyint(1) NOT NULL DEFAULT 0,
  `policy_version` varchar(20) NOT NULL DEFAULT '1',
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `granted_at` datetime DEFAULT NULL,
  `revoked_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`tracking_user_consent_id`),
  KEY `idx_tracking_consent_user` (`user_id`,`created_at`),
  KEY `idx_tracking_consent_guest` (`guest_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
