CREATE TABLE IF NOT EXISTS academy_term_invoice_payments (
  payment_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  invoice_id BIGINT UNSIGNED NOT NULL,
  installment_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  gateway VARCHAR(30) NOT NULL DEFAULT 'zarinpal',
  amount BIGINT UNSIGNED NOT NULL,
  currency ENUM('IRT','IRR') NOT NULL DEFAULT 'IRT',
  callback_token CHAR(64) NOT NULL,
  authority VARCHAR(64) NULL,
  reference_id VARCHAR(64) NULL,
  card_pan VARCHAR(32) NULL,
  card_hash VARCHAR(128) NULL,
  status ENUM('created','pending','paid','failed','canceled') NOT NULL DEFAULT 'created',
  gateway_code INT NULL,
  gateway_message VARCHAR(500) NULL,
  requested_at DATETIME NULL,
  verified_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_at DATETIME NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  deleted_at DATETIME NULL,
  deleted_by BIGINT UNSIGNED NULL,
  UNIQUE KEY uq_invoice_payment_callback_token (callback_token),
  UNIQUE KEY uq_invoice_payment_authority (authority),
  KEY idx_invoice_payment_installment (installment_id,status),
  KEY idx_invoice_payment_invoice (invoice_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
