CREATE TABLE IF NOT EXISTS f_social_bookmarks (
 user_id BIGINT UNSIGNED NOT NULL, kind VARCHAR(12) NOT NULL, target_id BIGINT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(user_id,kind,target_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS p_social_lesson_progress (
 user_id BIGINT UNSIGNED NOT NULL, course_id BIGINT UNSIGNED NOT NULL, post_id INT UNSIGNED NOT NULL,
 completed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(user_id,course_id,post_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS f_social_account_settings (
 user_id BIGINT UNSIGNED PRIMARY KEY, settings_json TEXT NOT NULL CHECK (JSON_VALID(CAST(settings_json AS CHAR)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
