CREATE TABLE IF NOT EXISTS social_profiles (
 user_id BIGINT UNSIGNED PRIMARY KEY, display_name VARCHAR(180) NOT NULL DEFAULT '',
 bio TEXT NULL, avatar_id BIGINT UNSIGNED NULL, cover_id BIGINT UNSIGNED NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS social_follows (
 follower_id BIGINT UNSIGNED NOT NULL, following_id BIGINT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(follower_id,following_id), INDEX(following_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS social_media (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, owner_id BIGINT UNSIGNED NOT NULL,
 filename VARCHAR(80) NOT NULL, mime VARCHAR(80) NOT NULL, bytes BIGINT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(owner_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS social_posts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, owner_id BIGINT UNSIGNED NOT NULL,
 body TEXT NOT NULL, kind VARCHAR(10) NOT NULL DEFAULT 'post', media_id BIGINT UNSIGNED NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME NULL, deleted_at DATETIME NULL,
 INDEX(owner_id,id), INDEX(kind,expires_at), FOREIGN KEY(media_id) REFERENCES social_media(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS social_reactions (
 user_id BIGINT UNSIGNED NOT NULL, post_id BIGINT UNSIGNED NOT NULL, kind VARCHAR(10) NOT NULL,
 PRIMARY KEY(user_id,post_id,kind), FOREIGN KEY(post_id) REFERENCES social_posts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS social_notifications (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL,
 actor_id BIGINT UNSIGNED NOT NULL, kind VARCHAR(20) NOT NULL, target_id BIGINT UNSIGNED NOT NULL,
 body VARCHAR(255) NOT NULL, read_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX(user_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
