<div id="chat" class="section hidden h-[calc(100vh-10rem)]" data-admin-ui-native>
 <div class="flex h-full overflow-hidden rounded-3xl bg-white shadow dark:bg-slate-900 dark:text-slate-100">
  <aside class="flex w-full flex-col border-l dark:border-slate-700 md:w-80" id="chatSidebar"><div class="flex items-center justify-between border-b p-4 dark:border-slate-700"><div><h1 class="text-xl font-bold">گفتگوها</h1><p class="text-xs text-gray-400 dark:text-slate-400">پیام خصوصی و گروهی</p></div><button onclick="openNewChatModal()" class="h-10 w-10 rounded-xl bg-indigo-600 text-white"><i class="fas fa-plus"></i></button></div><div class="border-b p-3 dark:border-slate-700"><label class="flex items-center gap-2 rounded-xl border bg-gray-50 px-3 dark:border-slate-600 dark:bg-slate-800"><i class="fas fa-search text-sm text-gray-400"></i><input id="chatConversationSearch" type="search" oninput="filterChatConversations()" placeholder="جستجوی گفتگو..." class="min-w-0 flex-1 bg-transparent py-2.5 text-sm outline-none placeholder:text-gray-400"></label></div><div id="chatConversationList" class="flex-1 space-y-1 overflow-y-auto p-2"></div></aside>
  <section class="hidden min-w-0 flex-1 flex-col dark:bg-slate-900 md:flex" id="chatRoom">
   <header class="flex items-center gap-3 border-b p-4 dark:border-slate-700"><button onclick="closeMobileChat()" class="md:hidden"><i class="fas fa-arrow-right"></i></button><div id="chatRoomAvatar" class="flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-full bg-indigo-100 font-bold text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">؟</div><button type="button" onclick="openChatDetails()" class="rounded-xl px-2 py-1 text-right hover:bg-gray-50 dark:hover:bg-slate-800"><h2 id="chatRoomTitle" class="font-bold">یک گفتگو را انتخاب کنید</h2><p id="chatRoomMeta" class="text-xs text-gray-400 dark:text-slate-400"></p></button></header>
   <div id="chatMessages" class="flex flex-1 flex-col gap-2 overflow-y-auto bg-slate-50 p-4 dark:bg-slate-950"></div>
   <div id="chatEditState" class="hidden border-t border-indigo-100 bg-indigo-50 px-4 py-2 text-xs text-indigo-700 dark:border-indigo-900 dark:bg-indigo-950 dark:text-indigo-300"><div class="flex items-center justify-between"><span><i class="fas fa-pencil-alt ml-2"></i>در حال ویرایش پیام</span><button type="button" onclick="cancelChatMessageEdit()" class="rounded-lg px-2 py-1 hover:bg-indigo-100 dark:hover:bg-indigo-900">لغو</button></div></div>
   <div id="chatVoicePreview" class="hidden items-center gap-3 border-t px-4 py-2 dark:border-slate-700"><audio id="chatVoiceAudio" class="h-10 min-w-0 flex-1" controls preload="metadata"></audio><span id="chatVoiceDuration" dir="ltr" class="shrink-0 text-xs text-gray-500 dark:text-slate-400"></span><button type="button" onclick="discardChatVoice()" title="حذف صدای ضبط‌شده" class="h-9 w-9 shrink-0 rounded-xl text-red-600 hover:bg-red-50 dark:hover:bg-red-950"><i class="fas fa-trash"></i></button></div>
   <form id="chatSendForm" onsubmit="sendChatMessage(event)" class="flex items-end gap-2 border-t p-3 dark:border-slate-700"><label class="flex h-11 w-11 shrink-0 cursor-pointer items-center justify-center rounded-xl border dark:border-slate-600 dark:bg-slate-800"><i class="fas fa-paperclip"></i><input id="chatFile" type="file" class="hidden" onchange="showChatFileName()"></label><button id="chatVoiceButton" type="button" onclick="toggleChatVoiceRecording()" title="ضبط صدا" aria-label="ضبط صدا" class="relative flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border dark:border-slate-600 dark:bg-slate-800"><i class="fas fa-microphone"></i><span id="chatVoiceTimer" dir="ltr" class="absolute -top-7 hidden rounded-full bg-red-600 px-2 py-1 text-[10px] text-white shadow">00:00</span></button><textarea id="chatBody" rows="1" placeholder="پیام بنویسید..." class="max-h-32 min-h-11 flex-1 resize-none rounded-2xl border px-4 py-3 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-100"></textarea><button id="chatSendButton" class="h-11 w-11 shrink-0 rounded-xl bg-indigo-600 text-white"><i class="fas fa-paper-plane"></i></button></form>
   <p id="chatFileName" class="hidden border-t px-4 py-2 text-xs text-indigo-600 dark:border-slate-700 dark:text-indigo-300"></p>
  </section>
 </div>
</div>
