<div id="tracking" class="section hidden space-y-6">
    <div class="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><h1 class="text-3xl font-bold">تحلیل رفتار کاربران</h1><p class="mt-1 text-gray-500">بررسی استفاده از امکانات، ماندگاری، تعامل، مسیرها و داده‌های خام Tracking</p></div><div class="flex flex-wrap gap-3 rounded-2xl bg-white p-3 shadow-sm"><select id="trackingDays" onchange="loadTrackingAnalytics()" class="rounded-xl border px-4 py-2.5"><option value="1">۲۴ ساعت اخیر</option><option value="7">۷ روز اخیر</option><option value="30" selected>۳۰ روز اخیر</option><option value="90">۹۰ روز اخیر</option><option value="all">همه زمان‌ها</option></select><select id="trackingUser" onchange="loadTrackingAnalytics()" class="min-w-52 rounded-xl border px-4 py-2.5"><option value="0">همه کاربران</option></select><button onclick="loadTrackingAnalytics()" class="rounded-xl bg-indigo-600 px-5 py-2.5 text-white"><i class="fas fa-sync-alt ml-2"></i>به‌روزرسانی</button></div></div>
    <div id="trackingLoading" class="rounded-3xl bg-white p-12 text-center text-gray-400">در حال تحلیل داده‌های رفتاری...</div>
    <div id="trackingContent" class="hidden space-y-6">
        <div id="trackingMetrics" class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"></div>
        <div id="trackingInsights" class="grid gap-4 lg:grid-cols-3"></div>
        <div class="grid gap-6 xl:grid-cols-3"><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">قیف تعامل</h2><div id="trackingFunnel" class="space-y-3"></div></section><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">بازگشت کاربران</h2><div id="trackingRetention"></div></section><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">کیفیت نشست‌ها</h2><div id="trackingSegments" class="space-y-3"></div></section></div>
        <div class="grid gap-6 xl:grid-cols-2"><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">روند نشست‌ها و بازدیدها</h2><div id="trackingTrend" class="h-72"></div></section><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">توزیع نوع فعالیت</h2><div id="trackingActivity" class="space-y-4"></div></section></div>
        <div class="grid gap-6 xl:grid-cols-2"><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">ساعات اوج استفاده</h2><div id="trackingHourly" class="grid grid-cols-6 gap-2 sm:grid-cols-8 xl:grid-cols-12"></div></section><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">روزهای فعال هفته</h2><div id="trackingWeekdays" class="space-y-3"></div></section></div>
        <div class="grid gap-6 xl:grid-cols-2"><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">محبوب‌ترین صفحات</h2><div id="trackingPopular"></div></section><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">صفحات کم‌علاقه</h2><div id="trackingUnpopular"></div></section></div>
        <div class="grid gap-6 xl:grid-cols-2"><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">امکانات و رویدادهای پرکاربرد</h2><div id="trackingFeatures"></div></section><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">تعامل با بخش‌های محتوا</h2><div id="trackingSections"></div></section></div>
        <div class="grid gap-6 xl:grid-cols-2"><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">صفحات ورودی</h2><div id="trackingEntries"></div></section><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">صفحات خروج</h2><div id="trackingExits"></div></section></div>
        <section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">مسیرهای پرتکرار کاربران</h2><div id="trackingTransitions"></div></section>
        <div class="grid gap-6 xl:grid-cols-2"><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">عناصر پرکلیک</h2><div id="trackingClicks"></div></section><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">تعامل و تکمیل فرم‌ها</h2><div id="trackingForms"></div></section></div>
        <section class="rounded-3xl border border-rose-100 bg-white p-6 shadow-sm"><h2 class="mb-2 text-xl font-bold text-rose-700">نقاط احتمالی اصطکاک و ریزش</h2><p class="mb-5 text-sm text-gray-500">ترکیب خروج، زمان مخفی یا بیکار و عمق کم اسکرول؛ این موارد برای بازبینی UX اولویت دارند.</p><div id="trackingFriction"></div></section>
        <div class="grid gap-6 xl:grid-cols-2"><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">منابع ورودی</h2><div id="trackingReferrers"></div></section><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">کمپین‌ها و UTM</h2><div id="trackingCampaigns"></div></section></div>
        <div class="grid gap-6 xl:grid-cols-3"><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">دستگاه‌ها</h2><div id="trackingDevices" class="space-y-3"></div></section><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">مرورگرها</h2><div id="trackingBrowsers" class="space-y-3"></div></section><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">رضایت‌نامه‌ها</h2><div id="trackingConsents"></div></section></div>
        <div class="grid gap-6 xl:grid-cols-3"><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">سلامت فنی</h2><div id="trackingTechnical"></div></section><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">زبان کاربران</h2><div id="trackingLocales" class="space-y-3"></div></section><section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">موقعیت کاربران</h2><div id="trackingLocations"></div></section></div>
        <section class="rounded-3xl bg-white p-6 shadow-sm"><h2 class="mb-5 text-xl font-bold">فعال‌ترین کاربران</h2><div id="trackingUsers" class="overflow-x-auto"></div></section>
        <section class="overflow-hidden rounded-3xl bg-white shadow-sm"><div class="border-b p-5"><h2 class="text-xl font-bold">بازبینی داده‌های خام</h2><p class="mt-1 text-sm text-gray-500">۵۰ رکورد آخر هر جدول در بازه انتخاب‌شده</p><div id="trackingRawTabs" class="mt-4 flex flex-wrap gap-2"></div></div><div id="trackingRawTable" class="overflow-x-auto p-5"></div></section>
    </div>
</div>
