<?php
namespace Modules\Analytics\Services;
final class AdminTrackingService{
    public function data(array $filters):array{
        $days=in_array((string)($filters['days']??'30'),['1','7','30','90','all'],true)?(string)$filters['days']:'30';$user=max(0,(int)($filters['user']??0));$since=$days==='all'?null:date('Y-m-d H:i:s',strtotime('-'.(int)$days.' days'));
        $sessionScope=$this->scope('s','started_at',$since,$user);$pageScope=$this->scope('p','entered_at',$since,$user);$transitionScope=$this->scope('p1','entered_at',$since,$user);$eventScope=$this->scope('e','occurred_at',$since,$user);$engagementScope=$this->scope('g','created_at',$since,$user);$activityScope=$this->scope('a','started_at',$since,$user);$consentScope=$this->scope('c','created_at',$since,$user);
        $session=$this->one("SELECT COUNT(*) sessions,COUNT(DISTINCT user_id) users,SUM(user_id IS NULL) guest_sessions,COALESCE(AVG(COALESCE(total_duration,0)),0) avg_duration,COALESCE(AVG(COALESCE(page_views_count,0)),0) pages_per_session,COALESCE(AVG(COALESCE(events_count,0)),0) events_per_session,COALESCE(AVG(COALESCE(engagement_score,0)),0) engagement_score,COALESCE(AVG(COALESCE(is_bounced,0))*100,0) bounce_rate FROM tracking_user_sessions s WHERE s.is_bot=0{$sessionScope['sql']}",$sessionScope['bindings']);
        $page=$this->one("SELECT COUNT(*) page_views,COALESCE(AVG(COALESCE(NULLIF(visible_duration_ms,0),total_duration_ms)),0) avg_visible_ms,COALESCE(AVG(COALESCE(max_scroll_depth,scroll_depth,0)),0) avg_scroll,COALESCE(SUM(interaction_count),0) interactions,COALESCE(SUM(click_count),0) clicks FROM tracking_user_page_views p WHERE 1=1{$pageScope['sql']}",$pageScope['bindings']);
        $events=(int)$this->scalar("SELECT COUNT(*) FROM tracking_user_events e WHERE 1=1{$eventScope['sql']}",$eventScope['bindings']);
        $metrics=['sessions'=>(int)$session['sessions'],'users'=>(int)$session['users'],'guestSessions'=>(int)$session['guest_sessions'],'pageViews'=>(int)$page['page_views'],'events'=>$events,'avgSessionMs'=>(int)$session['avg_duration']*1000,'avgPageMs'=>(int)$page['avg_visible_ms'],'pagesPerSession'=>round((float)$session['pages_per_session'],2),'eventsPerSession'=>round((float)$session['events_per_session'],2),'bounceRate'=>round((float)$session['bounce_rate'],1),'avgScroll'=>round((float)$page['avg_scroll'],1),'interactions'=>(int)$page['interactions'],'clicks'=>(int)$page['clicks']];
        $popular=$this->rows("SELECT COALESCE(NULLIF(page_type,''),NULLIF(page_title,''),page_path,'بدون عنوان') label,COALESCE(NULLIF(page_path,''),page_url) path,COUNT(*) views,COUNT(DISTINCT tracking_user_session_id) sessions,ROUND(AVG(COALESCE(NULLIF(visible_duration_ms,0),total_duration_ms))/1000,1) avg_seconds,ROUND(AVG(COALESCE(max_scroll_depth,scroll_depth,0)),1) avg_scroll,SUM(interaction_count) interactions,ROUND(AVG(is_exit_page)*100,1) exit_rate FROM tracking_user_page_views p WHERE 1=1{$pageScope['sql']} GROUP BY label,path ORDER BY views DESC LIMIT 15",$pageScope['bindings']);
        $unpopular=$this->rows("SELECT COALESCE(NULLIF(page_type,''),NULLIF(page_title,''),page_path,'بدون عنوان') label,COALESCE(NULLIF(page_path,''),page_url) path,COUNT(*) views,ROUND(AVG(COALESCE(NULLIF(visible_duration_ms,0),total_duration_ms))/1000,1) avg_seconds,ROUND(AVG(COALESCE(max_scroll_depth,scroll_depth,0)),1) avg_scroll,SUM(interaction_count) interactions,ROUND((AVG(COALESCE(NULLIF(visible_duration_ms,0),total_duration_ms))/1000)+AVG(COALESCE(max_scroll_depth,scroll_depth,0))/10+SUM(interaction_count)/COUNT(*),1) interest_score FROM tracking_user_page_views p WHERE 1=1{$pageScope['sql']} GROUP BY label,path HAVING views>=2 ORDER BY interest_score ASC,views ASC LIMIT 10",$pageScope['bindings']);
        $features=$this->rows("SELECT COALESCE(NULLIF(section_key,''),NULLIF(event_action,''),event_name) label,event_name,COUNT(*) uses,COUNT(DISTINCT user_id) users,COUNT(DISTINCT tracking_user_session_id) sessions,ROUND(AVG(COALESCE(duration_ms,0))/1000,1) avg_seconds FROM tracking_user_events e WHERE event_name NOT IN ('heartbeat','page_view','page_leave'){$eventScope['sql']} GROUP BY label,event_name ORDER BY uses DESC LIMIT 15",$eventScope['bindings']);
        $sections=$this->rows("SELECT section_key label,COUNT(*) records,SUM(impression_count) impressions,ROUND(SUM(visible_duration_ms)/1000,1) visible_seconds,ROUND(SUM(active_duration_ms)/1000,1) active_seconds,SUM(interaction_count) interactions,SUM(click_count) clicks,ROUND(AVG(max_visibility_percent),1) visibility FROM tracking_user_content_engagements g WHERE section_key<>''{$engagementScope['sql']} GROUP BY section_key ORDER BY active_seconds DESC LIMIT 15",$engagementScope['bindings']);
        $trend=$this->rows("SELECT DATE(started_at) day,COUNT(*) sessions,COUNT(DISTINCT user_id) users,SUM(page_views_count) page_views,SUM(events_count) events,ROUND(AVG(is_bounced)*100,1) bounce_rate FROM tracking_user_sessions s WHERE s.is_bot=0{$sessionScope['sql']} GROUP BY DATE(started_at) ORDER BY day",$sessionScope['bindings']);
        $devices=$this->rows("SELECT COALESCE(device_type,'unknown') label,COUNT(*) value FROM tracking_user_sessions s WHERE s.is_bot=0{$sessionScope['sql']} GROUP BY device_type ORDER BY value DESC",$sessionScope['bindings']);
        $browsers=$this->rows("SELECT COALESCE(browser,'unknown') label,COUNT(*) value FROM tracking_user_sessions s WHERE s.is_bot=0{$sessionScope['sql']} GROUP BY browser ORDER BY value DESC LIMIT 8",$sessionScope['bindings']);
        $activity=$this->rows("SELECT activity_type label,ROUND(SUM(COALESCE(duration_ms,0))/1000,1) seconds,COUNT(*) intervals FROM tracking_user_activity_intervals a WHERE 1=1{$activityScope['sql']} GROUP BY activity_type ORDER BY seconds DESC",$activityScope['bindings']);
        $users=$this->rows("SELECT s.user_id id,COALESCE((SELECT value FROM translations t WHERE t.table_name='users' AND t.table_id=s.user_id AND t.field='full_name' AND t.locale='fa' AND t.deleted_at IS NULL ORDER BY t.translation_id DESC LIMIT 1),u.username,CONCAT('کاربر ',s.user_id)) name,COUNT(*) sessions,SUM(s.page_views_count) page_views,SUM(s.events_count) events,ROUND(SUM(s.active_duration_ms)/60000,1) active_minutes,ROUND(AVG(s.is_bounced)*100,1) bounce_rate FROM tracking_user_sessions s LEFT JOIN users u ON u.user_id=s.user_id WHERE s.user_id IS NOT NULL AND s.is_bot=0{$sessionScope['sql']} GROUP BY s.user_id,u.username ORDER BY active_minutes DESC LIMIT 15",$sessionScope['bindings']);
        $consents=$this->one("SELECT COUNT(*) total,SUM(analytics_allowed=1) analytics,SUM(personalization_allowed=1) personalization,SUM(marketing_allowed=1) marketing,SUM(revoked_at IS NOT NULL) revoked FROM tracking_user_consents c WHERE 1=1{$consentScope['sql']}",$consentScope['bindings']);
        $quality=$this->one("SELECT COUNT(*) total,SUM(page_views_count>1) multi_page,SUM(active_duration_ms>=60000) engaged,SUM(active_duration_ms>=300000) deep_engaged,SUM(status IN ('ended','expired')) completed,SUM(end_reason IN ('timeout','network_lost','browser_closed')) interrupted FROM tracking_user_sessions s WHERE s.is_bot=0{$sessionScope['sql']}",$sessionScope['bindings']);
        $converted=(int)$this->scalar("SELECT COUNT(DISTINCT tracking_user_session_id) FROM tracking_user_events e WHERE event_name='form_submit'{$eventScope['sql']}",$eventScope['bindings']);
        $focused=(int)$this->scalar("SELECT COUNT(DISTINCT tracking_user_session_id) FROM tracking_user_events e WHERE event_name='field_focus'{$eventScope['sql']}",$eventScope['bindings']);
        $interacted=(int)$this->scalar("SELECT COUNT(DISTINCT tracking_user_session_id) FROM tracking_user_events e WHERE event_name IN ('click','field_focus','keypress','form_submit'){$eventScope['sql']}",$eventScope['bindings']);
        $funnel=[['label'=>'شروع نشست','value'=>(int)$quality['total']],['label'=>'اولین تعامل','value'=>$interacted],['label'=>'تعامل با فرم','value'=>$focused],['label'=>'ارسال فرم','value'=>$converted]];
        $retention=$this->one("SELECT COUNT(*) users,SUM(session_count>1) returning_users,ROUND(AVG(session_count),2) avg_sessions,ROUND(AVG(active_days),2) avg_active_days FROM (SELECT user_id,COUNT(*) session_count,COUNT(DISTINCT DATE(started_at)) active_days FROM tracking_user_sessions s WHERE user_id IS NOT NULL AND is_bot=0{$sessionScope['sql']} GROUP BY user_id) x",$sessionScope['bindings']);
        $sessionSegments=[['label'=>'خروج سریع','value'=>(int)$session['sessions']?(int)round((float)$session['bounce_rate']*(int)$session['sessions']/100):0],['label'=>'مرور چندصفحه‌ای','value'=>(int)$quality['multi_page']],['label'=>'تعامل بالای یک دقیقه','value'=>(int)$quality['engaged']],['label'=>'تعامل عمیق بالای پنج دقیقه','value'=>(int)$quality['deep_engaged']]];
        $entryPages=$this->rows("SELECT COALESCE(NULLIF(entry_page,''),'نامشخص') label,COUNT(*) sessions,ROUND(AVG(is_bounced)*100,1) bounce_rate,ROUND(AVG(COALESCE(total_duration,0)),1) avg_seconds FROM tracking_user_sessions s WHERE s.is_bot=0{$sessionScope['sql']} GROUP BY label ORDER BY sessions DESC LIMIT 12",$sessionScope['bindings']);
        $exitPages=$this->rows("SELECT COALESCE(NULLIF(exit_page,''),'نامشخص') label,COUNT(*) exits,ROUND(AVG(COALESCE(total_duration,0)),1) avg_seconds FROM tracking_user_sessions s WHERE s.is_bot=0{$sessionScope['sql']} GROUP BY label ORDER BY exits DESC LIMIT 12",$sessionScope['bindings']);
        $referrers=$this->rows("SELECT COALESCE(NULLIF(referrer_domain,''),'ورود مستقیم') label,COUNT(*) views,COUNT(DISTINCT tracking_user_session_id) sessions,ROUND(AVG(COALESCE(NULLIF(visible_duration_ms,0),total_duration_ms))/1000,1) avg_seconds FROM tracking_user_page_views p WHERE 1=1{$pageScope['sql']} GROUP BY label ORDER BY sessions DESC LIMIT 12",$pageScope['bindings']);
        $campaigns=$this->rows("SELECT COALESCE(NULLIF(utm_source,''),'بدون UTM') source,COALESCE(NULLIF(utm_medium,''),'—') medium,COALESCE(NULLIF(utm_campaign,''),'—') campaign,COUNT(*) views,COUNT(DISTINCT tracking_user_session_id) sessions FROM tracking_user_page_views p WHERE 1=1{$pageScope['sql']} GROUP BY source,medium,campaign ORDER BY sessions DESC LIMIT 12",$pageScope['bindings']);
        $hourly=$this->rows("SELECT HOUR(started_at) hour,COUNT(*) sessions,COUNT(DISTINCT user_id) users,ROUND(AVG(COALESCE(total_duration,0)),1) avg_seconds FROM tracking_user_sessions s WHERE s.is_bot=0{$sessionScope['sql']} GROUP BY HOUR(started_at) ORDER BY hour",$sessionScope['bindings']);
        $weekdays=$this->rows("SELECT WEEKDAY(started_at) weekday,COUNT(*) sessions,SUM(page_views_count) page_views,SUM(events_count) events FROM tracking_user_sessions s WHERE s.is_bot=0{$sessionScope['sql']} GROUP BY WEEKDAY(started_at) ORDER BY weekday",$sessionScope['bindings']);
        $transitions=$this->rows("SELECT COALESCE(NULLIF(p1.page_type,''),p1.page_path) source,COALESCE(NULLIF(p2.page_type,''),p2.page_path) destination,COUNT(*) transitions FROM tracking_user_page_views p1 JOIN tracking_user_page_views p2 ON p2.tracking_user_session_id=p1.tracking_user_session_id AND p2.sequence_number=p1.sequence_number+1 WHERE 1=1{$transitionScope['sql']} GROUP BY source,destination ORDER BY transitions DESC LIMIT 15",$transitionScope['bindings']);
        $clickedTargets=$this->rows("SELECT COALESCE(NULLIF(target_text,''),NULLIF(target_name,''),NULLIF(target_id,''),NULLIF(section_key,''),'عنصر نامشخص') label,COALESCE(NULLIF(section_key,''),'—') section,COUNT(*) clicks,COUNT(DISTINCT user_id) users,COUNT(DISTINCT tracking_user_session_id) sessions FROM tracking_user_events e WHERE event_name='click'{$eventScope['sql']} GROUP BY label,section ORDER BY clicks DESC LIMIT 15",$eventScope['bindings']);
        $forms=$this->rows("SELECT COALESCE(NULLIF(section_key,''),NULLIF(target_name,''),NULLIF(target_id,''),'فرم نامشخص') label,SUM(event_name='field_focus') focuses,SUM(event_name='form_submit') submits,COUNT(DISTINCT tracking_user_session_id) sessions FROM tracking_user_events e WHERE event_name IN ('field_focus','form_submit'){$eventScope['sql']} GROUP BY label ORDER BY focuses DESC LIMIT 15",$eventScope['bindings']);
        $friction=$this->rows("SELECT COALESCE(NULLIF(page_type,''),NULLIF(page_title,''),page_path) label,COUNT(*) views,ROUND(AVG(hidden_duration_ms/NULLIF(total_duration_ms,0))*100,1) hidden_rate,ROUND(AVG(idle_duration_ms/NULLIF(total_duration_ms,0))*100,1) idle_rate,ROUND(AVG(COALESCE(max_scroll_depth,0)),1) scroll_depth,ROUND(AVG(is_exit_page)*100,1) exit_rate,SUM(form_interaction_count) form_interactions FROM tracking_user_page_views p WHERE total_duration_ms>0{$pageScope['sql']} GROUP BY label HAVING COUNT(*)>=2 ORDER BY (COALESCE(AVG(hidden_duration_ms/NULLIF(total_duration_ms,0))*100,0)+COALESCE(AVG(idle_duration_ms/NULLIF(total_duration_ms,0))*100,0)+AVG(is_exit_page)*100+(100-AVG(COALESCE(max_scroll_depth,0)))) DESC LIMIT 12",$pageScope['bindings']);
        $technical=$this->one("SELECT SUM(event_name='network_offline') offline_events,SUM(event_name='network_online') online_events,COUNT(DISTINCT CASE WHEN event_name='network_offline' THEN tracking_user_session_id END) affected_sessions FROM tracking_user_events e WHERE event_name IN ('network_offline','network_online'){$eventScope['sql']}",$eventScope['bindings']);
        $formAbandonment=['focusedSessions'=>$focused,'submittedSessions'=>$converted,'abandonedSessions'=>max(0,$focused-$converted),'completionRate'=>$focused?round($converted*100/$focused,1):0];
        $locales=$this->rows("SELECT COALESCE(NULLIF(language,''),'نامشخص') label,COUNT(*) value FROM tracking_user_sessions s WHERE s.is_bot=0{$sessionScope['sql']} GROUP BY label ORDER BY value DESC",$sessionScope['bindings']);
        $locations=$this->rows("SELECT COALESCE(NULLIF(country_code,''),'نامشخص') country,COALESCE(NULLIF(city_name,''),'نامشخص') city,COUNT(*) sessions FROM tracking_user_sessions s WHERE s.is_bot=0{$sessionScope['sql']} GROUP BY country,city ORDER BY sessions DESC LIMIT 12",$sessionScope['bindings']);
        $raw=['sessions'=>$this->raw('tracking_user_sessions','tracking_user_session_id','started_at',$since,$user),'pageViews'=>$this->raw('tracking_user_page_views','tracking_user_page_view_id','entered_at',$since,$user),'events'=>$this->raw('tracking_user_events','tracking_user_event_id','occurred_at',$since,$user),'engagements'=>$this->raw('tracking_user_content_engagements','tracking_user_content_engagement_id','created_at',$since,$user),'activities'=>$this->raw('tracking_user_activity_intervals','tracking_user_activity_interval_id','started_at',$since,$user),'consents'=>$this->raw('tracking_user_consents','tracking_user_consent_id','created_at',$since,$user),'batches'=>$this->rawBatches($since,$user)];
        return compact('days','user','metrics','popular','unpopular','features','sections','trend','devices','browsers','activity','users','consents','quality','funnel','retention','sessionSegments','entryPages','exitPages','referrers','campaigns','hourly','weekdays','transitions','clickedTargets','forms','friction','technical','formAbandonment','locales','locations','raw')+['userOptions'=>$this->userOptions()];
    }
    private function scope(string$a,string$date,?string$since,int$user):array{$sql='';$b=[];if($since){$sql.=" AND {$a}.{$date}>=?";$b[]=$since;}if($user){$sql.=" AND {$a}.user_id=?";$b[]=$user;}return['sql'=>$sql,'bindings'=>$b];}
    private function raw(string$table,string$id,string$date,?string$since,int$user):array{$where=[];$b=[];if($since){$where[]="{$date}>=?";$b[]=$since;}if($user){$where[]='user_id=?';$b[]=$user;}$sql="SELECT * FROM {$table}".($where?' WHERE '.implode(' AND ',$where):'')." ORDER BY {$id} DESC LIMIT 50";return$this->rows($sql,$b);}
    private function rawBatches(?string$since,int$user):array{$where=[];$b=[];if($since){$where[]='b.created_at>=?';$b[]=$since;}if($user){$where[]='s.user_id=?';$b[]=$user;}return$this->rows('SELECT b.* FROM tracking_ingestion_batches b JOIN tracking_user_sessions s ON s.tracking_user_session_id=b.tracking_user_session_id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY b.tracking_ingestion_batch_id DESC LIMIT 50',$b);}
    private function userOptions():array{return$this->rows("SELECT DISTINCT s.user_id id,COALESCE((SELECT value FROM translations t WHERE t.table_name='users' AND t.table_id=s.user_id AND t.field='full_name' AND t.locale='fa' AND t.deleted_at IS NULL ORDER BY t.translation_id DESC LIMIT 1),u.username,CONCAT('کاربر ',s.user_id)) name FROM tracking_user_sessions s LEFT JOIN users u ON u.user_id=s.user_id WHERE s.user_id IS NOT NULL ORDER BY name");}
    private function rows(string$sql,array$b=[]):array{$q=db()->prepare($sql);$q->execute($b);return$q->fetchAll();}private function one(string$sql,array$b=[]):array{return$this->rows($sql,$b)[0]??[];}private function scalar(string$sql,array$b=[]):mixed{$q=db()->prepare($sql);$q->execute($b);return$q->fetchColumn();}
}
