<?php

namespace Modules\Analytics\Services;

use Core\database\DB;
use Modules\System\Services\SiteAdminAccess;
use RuntimeException;

class AdminDashboardService
{
    public function data(int $actor, array $filters = []): array
    {
        $branchId = max(0, (int)($filters['branchId'] ?? 0));
        $locale = locale() === 'en' ? 'en' : 'fa';
        $allowedIds = $this->allowedBranchIds($actor);
        if ($branchId && !in_array($branchId, $allowedIds, true)) throw new RuntimeException('شما به این شعبه دسترسی ندارید.');
        $scopeIds = $branchId ? [$branchId] : $allowedIds;
        $scopeSql = $scopeIds ? implode(',', $scopeIds) : '0';
        $branch = " AND c.branch_id IN ({$scopeSql})";
        $memberBranch = " AND m.branch_id IN ({$scopeSql})";
        $today = date('Y-m-d');
        $monthStart = date('Y-m-01 00:00:00');
        $weekStart = date('Y-m-d 00:00:00', strtotime('-6 days'));

        $allowedSql = $allowedIds ? implode(',', $allowedIds) : '0';
        $branches = $this->rows("SELECT b.branch_id id,COALESCE((SELECT value FROM translations WHERE table_name='academy_branches' AND table_id=b.branch_id AND field='name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),CONCAT('شعبه ',b.branch_id)) name FROM academy_branches b WHERE b.deleted_at IS NULL AND b.branch_id IN ({$allowedSql}) ORDER BY name");

        $activeStudents = $this->value("SELECT COUNT(DISTINCT m.user_id) FROM academy_branch_members m JOIN academy_branch_course_term_enrollments e ON e.member_id=m.member_id AND e.type='student' AND e.status='active' AND e.deleted_at IS NULL WHERE m.deleted_at IS NULL{$memberBranch}");
        $todayClasses = $this->value("SELECT COUNT(*) FROM academy_branch_course_term_sessions s JOIN academy_branch_bookings b ON b.booking_id=s.booking_id AND b.deleted_at IS NULL JOIN academy_branch_course_terms t ON t.term_id=s.term_id AND t.deleted_at IS NULL JOIN academy_branch_courses c ON c.course_id=t.course_id AND c.deleted_at IS NULL WHERE s.deleted_at IS NULL AND b.requested_date=?{$branch}", [$today]);
        $monthlyIncome = $this->value("SELECT COALESCE(SUM(i.amount),0) FROM academy_branch_course_term_invoice_installments i JOIN academy_branch_course_term_invoices f ON f.term_invoice_id=i.invoice_id AND f.deleted_at IS NULL JOIN academy_branch_course_terms t ON t.term_id=f.term_id AND t.deleted_at IS NULL JOIN academy_branch_courses c ON c.course_id=t.course_id AND c.deleted_at IS NULL WHERE i.deleted_at IS NULL AND i.status='paid' AND i.paid_at>=?{$branch}", [$monthStart]);
        $attendanceTotal = $this->value("SELECT COUNT(*) FROM academy_branch_course_term_session_attendances a JOIN academy_branch_course_term_sessions s ON s.term_session_id=a.session_id AND s.deleted_at IS NULL JOIN academy_branch_bookings b ON b.booking_id=s.booking_id AND b.deleted_at IS NULL JOIN academy_branch_course_terms t ON t.term_id=s.term_id AND t.deleted_at IS NULL JOIN academy_branch_courses c ON c.course_id=t.course_id AND c.deleted_at IS NULL WHERE a.deleted_at IS NULL AND b.requested_date>=?{$branch}", [date('Y-m-01')]);
        $attendancePresent = $this->value("SELECT COUNT(*) FROM academy_branch_course_term_session_attendances a JOIN academy_branch_course_term_sessions s ON s.term_session_id=a.session_id AND s.deleted_at IS NULL JOIN academy_branch_bookings b ON b.booking_id=s.booking_id AND b.deleted_at IS NULL JOIN academy_branch_course_terms t ON t.term_id=s.term_id AND t.deleted_at IS NULL JOIN academy_branch_courses c ON c.course_id=t.course_id AND c.deleted_at IS NULL WHERE a.deleted_at IS NULL AND a.status IN ('present','late','online') AND b.requested_date>=?{$branch}", [date('Y-m-01')]);
        $pendingPayments = $this->value("SELECT COUNT(*) FROM academy_branch_course_term_invoice_installments i JOIN academy_branch_course_term_invoices f ON f.term_invoice_id=i.invoice_id AND f.deleted_at IS NULL JOIN academy_branch_course_terms t ON t.term_id=f.term_id AND t.deleted_at IS NULL JOIN academy_branch_courses c ON c.course_id=t.course_id AND c.deleted_at IS NULL WHERE i.deleted_at IS NULL AND i.status<>'paid' AND i.due_date<?{$branch}", [$today]);
        $newMessages = $this->value("SELECT COUNT(*) FROM user_messages um WHERE um.deleted_at IS NULL AND um.is_read=0 AND EXISTS(SELECT 1 FROM academy_branch_members m WHERE m.user_id=um.sender_id AND m.branch_id IN ({$scopeSql}) AND m.deleted_at IS NULL)");
        $newStudentsWeek = $this->value("SELECT COUNT(*) FROM academy_branch_course_term_enrollments e JOIN academy_branch_members m ON m.member_id=e.member_id AND m.deleted_at IS NULL WHERE e.deleted_at IS NULL AND e.type='student' AND e.created_at>=?{$memberBranch}", [$weekStart]);
        $pointsAwarded = $this->value("SELECT COALESCE(SUM(ABS(p.points)),0) FROM user_points p WHERE p.deleted_at IS NULL AND p.points>0 AND p.created_at>=? AND EXISTS(SELECT 1 FROM academy_branch_members m WHERE m.user_id=p.user_id AND m.branch_id IN ({$scopeSql}) AND m.deleted_at IS NULL)", [$monthStart]);

        $classes = $this->rows("SELECT s.term_session_id,b.start_time,c.branch_id,COALESCE((SELECT value FROM translations WHERE table_name='academy_branches' AND table_id=c.branch_id AND field='name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),CONCAT('شعبه ',c.branch_id)) branch,COALESCE((SELECT value FROM translations WHERE table_name='lessons' AND table_id=c.lesson_id AND field='title' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),CONCAT('درس ',c.lesson_id)) instrument,(SELECT COUNT(*) FROM academy_branch_course_term_enrollments e WHERE e.term_id=t.term_id AND e.type='student' AND e.status='active' AND e.deleted_at IS NULL) student_count,(SELECT GROUP_CONCAT(COALESCE((SELECT value FROM translations WHERE table_name='users' AND table_id=m.user_id AND field='full_name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),u.username) SEPARATOR '، ') FROM academy_branch_course_term_enrollments e JOIN academy_branch_members m ON m.member_id=e.member_id AND m.deleted_at IS NULL JOIN users u ON u.user_id=m.user_id WHERE e.term_id=t.term_id AND e.type='student' AND e.status='active' AND e.deleted_at IS NULL) students,(SELECT COUNT(*) FROM academy_branch_course_term_enrollments e WHERE e.term_id=t.term_id AND e.type='teacher' AND e.status='active' AND e.deleted_at IS NULL) teacher_count,(SELECT GROUP_CONCAT(COALESCE((SELECT value FROM translations WHERE table_name='users' AND table_id=m.user_id AND field='full_name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),u.username) SEPARATOR '، ') FROM academy_branch_course_term_enrollments e JOIN academy_branch_members m ON m.member_id=e.member_id AND m.deleted_at IS NULL JOIN users u ON u.user_id=m.user_id WHERE e.term_id=t.term_id AND e.type='teacher' AND e.status='active' AND e.deleted_at IS NULL) teachers FROM academy_branch_course_term_sessions s JOIN academy_branch_bookings b ON b.booking_id=s.booking_id AND b.deleted_at IS NULL JOIN academy_branch_course_terms t ON t.term_id=s.term_id AND t.deleted_at IS NULL JOIN academy_branch_courses c ON c.course_id=t.course_id AND c.deleted_at IS NULL WHERE s.deleted_at IS NULL AND b.requested_date=?{$branch} ORDER BY b.start_time LIMIT 8", [$today]);
        $todayClassesList = array_map(fn($r) => ['time'=>substr((string)$r['start_time'],0,5),'student'=>(int)$r['student_count']>1?((int)$r['student_count'].' هنرجو'):($r['students']?:'بدون هنرجو'),'instrument'=>$r['instrument'],'teacher'=>(int)$r['teacher_count']>1?((int)$r['teacher_count'].' مدرس'):($r['teachers']?:'بدون مدرس'),'branch'=>$r['branch'],'branchId'=>(int)$r['branch_id']], $classes);

        $payments = $this->rows("SELECT i.amount,i.paid_at,c.branch_id,COALESCE((SELECT value FROM translations WHERE table_name='academy_branches' AND table_id=c.branch_id AND field='name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),CONCAT('شعبه ',c.branch_id)) branch,COALESCE((SELECT value FROM translations WHERE table_name='users' AND table_id=m.user_id AND field='full_name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),u.username,CONCAT('کاربر ',m.user_id)) name FROM academy_branch_course_term_invoice_installments i JOIN academy_branch_course_term_invoices f ON f.term_invoice_id=i.invoice_id AND f.deleted_at IS NULL JOIN academy_branch_course_terms t ON t.term_id=f.term_id AND t.deleted_at IS NULL JOIN academy_branch_courses c ON c.course_id=t.course_id AND c.deleted_at IS NULL LEFT JOIN academy_branch_members m ON m.member_id=f.member_id LEFT JOIN users u ON u.user_id=m.user_id WHERE i.deleted_at IS NULL AND i.status='paid'{$branch} ORDER BY i.paid_at DESC LIMIT 6");
        $recentPayments = array_map(fn($r)=>['name'=>$r['name'],'amount'=>$this->amount($r['amount']),'time'=>$this->relative($r['paid_at']),'branch'=>$r['branch'],'branchId'=>(int)$r['branch_id']],$payments);

        $deposits = $this->rows("SELECT p.amount,p.method,p.paid_at,c.branch_id,COALESCE((SELECT value FROM translations WHERE table_name='academy_branches' AND table_id=c.branch_id AND field='name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),CONCAT('شعبه ',c.branch_id)) branch FROM financial_system_payments p JOIN academy_branch_course_term_invoices f ON f.term_invoice_id=p.invoice_id AND f.deleted_at IS NULL JOIN academy_branch_course_terms t ON t.term_id=f.term_id AND t.deleted_at IS NULL JOIN academy_branch_courses c ON c.course_id=t.course_id AND c.deleted_at IS NULL WHERE p.deleted_at IS NULL AND p.status='completed'{$branch} ORDER BY p.paid_at DESC LIMIT 6");
        $methods=['cash'=>'نقدی','card'=>'کارت','bank_transfer'=>'انتقال بانکی','online'=>'آنلاین'];
        $recentDeposits=array_map(fn($r)=>['title'=>'واریز '.$methods[$r['method']]??'مالی','amount'=>$this->amount($r['amount']),'bank'=>$methods[$r['method']]??$r['method'],'time'=>$this->relative($r['paid_at']),'branch'=>$r['branch'],'branchId'=>(int)$r['branch_id']],$deposits);

        $absences=$this->rows("SELECT a.created_at,b.start_time,c.branch_id,COALESCE((SELECT value FROM translations WHERE table_name='academy_branches' AND table_id=c.branch_id AND field='name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),CONCAT('شعبه ',c.branch_id)) branch,COALESCE((SELECT value FROM translations WHERE table_name='lessons' AND table_id=c.lesson_id AND field='title' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),CONCAT('درس ',c.lesson_id)) instrument,COALESCE((SELECT value FROM translations WHERE table_name='users' AND table_id=m.user_id AND field='full_name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),u.username) student FROM academy_branch_course_term_session_attendances a JOIN academy_branch_course_term_sessions s ON s.term_session_id=a.session_id AND s.deleted_at IS NULL JOIN academy_branch_bookings b ON b.booking_id=s.booking_id AND b.deleted_at IS NULL JOIN academy_branch_course_terms t ON t.term_id=s.term_id AND t.deleted_at IS NULL JOIN academy_branch_courses c ON c.course_id=t.course_id AND c.deleted_at IS NULL JOIN academy_branch_members m ON m.member_id=a.member_id AND m.deleted_at IS NULL JOIN users u ON u.user_id=m.user_id WHERE a.deleted_at IS NULL AND a.status IN ('absent','excused_absence') AND b.requested_date=?{$branch} ORDER BY b.start_time DESC LIMIT 6",[$today]);
        $todayAbsences=array_map(fn($r)=>['student'=>$r['student'],'instrument'=>$r['instrument'],'teacher'=>'ثبت حضور و غیاب','time'=>substr((string)$r['start_time'],0,5),'branch'=>$r['branch'],'branchId'=>(int)$r['branch_id']],$absences);

        $messageBranch=" AND EXISTS(SELECT 1 FROM academy_branch_members bm WHERE bm.user_id=um.sender_id AND bm.branch_id IN ({$scopeSql}) AND bm.deleted_at IS NULL)";
        $messages=$this->rows("SELECT um.*,COALESCE((SELECT value FROM translations WHERE table_name='users' AND table_id=um.sender_id AND field='full_name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),u.username,CONCAT('کاربر ',um.sender_id)) sender,(SELECT bm.branch_id FROM academy_branch_members bm WHERE bm.user_id=um.sender_id AND bm.deleted_at IS NULL ORDER BY bm.member_id LIMIT 1) branch_id,(SELECT COALESCE((SELECT value FROM translations WHERE table_name='academy_branches' AND table_id=bm.branch_id AND field='name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),CONCAT('شعبه ',bm.branch_id)) FROM academy_branch_members bm WHERE bm.user_id=um.sender_id AND bm.deleted_at IS NULL ORDER BY bm.member_id LIMIT 1) branch FROM user_messages um LEFT JOIN users u ON u.user_id=um.sender_id WHERE um.deleted_at IS NULL AND um.is_read=0{$messageBranch} ORDER BY um.created_at DESC LIMIT 6");
        $unreadMessages=array_map(fn($r)=>['from'=>$r['sender'],'preview'=>$r['content'],'time'=>$this->relative($r['created_at']),'branch'=>$r['branch']?:'بدون شعبه','branchId'=>$r['branch_id']?(int)$r['branch_id']:null],$messages);

        $registrations=$this->rows("SELECT e.created_at,c.branch_id,COALESCE((SELECT value FROM translations WHERE table_name='academy_branches' AND table_id=c.branch_id AND field='name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),CONCAT('شعبه ',c.branch_id)) branch,COALESCE((SELECT value FROM translations WHERE table_name='lessons' AND table_id=c.lesson_id AND field='title' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),CONCAT('درس ',c.lesson_id)) instrument,COALESCE((SELECT value FROM translations WHERE table_name='users' AND table_id=m.user_id AND field='full_name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),u.username) name FROM academy_branch_course_term_enrollments e JOIN academy_branch_members m ON m.member_id=e.member_id AND m.deleted_at IS NULL JOIN users u ON u.user_id=m.user_id JOIN academy_branch_course_terms t ON t.term_id=e.term_id AND t.deleted_at IS NULL JOIN academy_branch_courses c ON c.course_id=t.course_id AND c.deleted_at IS NULL WHERE e.deleted_at IS NULL AND e.type='student'{$branch} ORDER BY e.created_at DESC LIMIT 6");
        $recentRegistrations=array_map(fn($r)=>['name'=>$r['name'],'instrument'=>$r['instrument'],'date'=>$this->relative($r['created_at']),'branch'=>$r['branch'],'branchId'=>(int)$r['branch_id']],$registrations);

        $holidayBranch=" AND m.branch_id IN ({$scopeSql})";
        $holidays=$this->rows("SELECT x.date,x.type,m.branch_id,COALESCE((SELECT value FROM translations WHERE table_name='academy_branches' AND table_id=m.branch_id AND field='name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),CONCAT('شعبه ',m.branch_id)) branch,COALESCE((SELECT value FROM translations WHERE table_name='users' AND table_id=x.user_id AND field='full_name' AND locale='{$locale}' AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),u.username) person FROM user_availability_exceptions x JOIN users u ON u.user_id=x.user_id LEFT JOIN academy_branch_members m ON m.user_id=x.user_id AND m.deleted_at IS NULL WHERE x.deleted_at IS NULL AND x.date>=?{$holidayBranch} GROUP BY x.user_availability_exception_id ORDER BY x.date LIMIT 6",[$today]);
        $types=['holiday'=>'تعطیلی','leave'=>'مرخصی','unavailable'=>'عدم دسترسی'];
        $upcomingHolidays=array_map(fn($r)=>['title'=>($types[$r['type']]??$r['type']).($r['person']?' '.$r['person']:''),'date'=>$r['date'],'branch'=>$r['branch']?:'بدون شعبه','branchId'=>$r['branch_id']?(int)$r['branch_id']:null],$holidays);

        $absencesToday=count($todayAbsences);$urgent=[];
        if($pendingPayments)$urgent[]=['type'=>'بدهی','text'=>$pendingPayments.' قسط معوق ثبت شده است','color'=>'rose','section'=>'finance','branchId'=>$branchId?:null];
        if($absencesToday)$urgent[]=['type'=>'غیبت','text'=>$absencesToday.' غیبت امروز ثبت شده است','color'=>'amber','section'=>'students','branchId'=>$branchId?:null];
        if($newMessages)$urgent[]=['type'=>'پیام','text'=>$newMessages.' پیام خوانده‌نشده وجود دارد','color'=>'indigo','section'=>'messages','branchId'=>$branchId?:null];
        $highNotifications=$this->value("SELECT COUNT(*) FROM user_notifications WHERE deleted_at IS NULL AND is_read=0 AND type IN ('database_delete','error','warning')");
        if($highNotifications)$urgent[]=['type'=>'اعلان','text'=>$highNotifications.' اعلان سیستمی مهم وجود دارد','color'=>'red','section'=>'notifications','branchId'=>null];

        return ['branches'=>$branches,'stats'=>['activeStudents'=>$activeStudents,'todayClasses'=>$todayClasses,'monthlyIncome'=>$this->amount($monthlyIncome),'attendanceRate'=>$attendanceTotal?round($attendancePresent*100/$attendanceTotal).'%':'۰٪','pendingPayments'=>$pendingPayments,'absencesToday'=>$absencesToday,'newMessages'=>$newMessages,'urgentAlerts'=>count($urgent),'newStudentsWeek'=>$newStudentsWeek,'pointsAwarded'=>$pointsAwarded],'todayClasses'=>$todayClassesList,'urgentItems'=>$urgent,'recentPayments'=>$recentPayments,'recentDeposits'=>$recentDeposits,'todayAbsences'=>$todayAbsences,'unreadMessages'=>$unreadMessages,'recentRegistrations'=>$recentRegistrations,'upcomingHolidays'=>$upcomingHolidays];
    }

    private function rows(string $sql,array $bindings=[]):array{$statement=db()->prepare($sql);$statement->execute($bindings);return $statement->fetchAll();}
    private function value(string $sql,array $bindings=[]):int|float{$statement=db()->prepare($sql);$statement->execute($bindings);return (float)$statement->fetchColumn();}
    private function amount(mixed $amount):string{return number_format((float)$amount,0,'.',',');}
    private function relative(?string $date):string{if(!$date)return '—';$seconds=max(0,time()-strtotime($date));if($seconds<60)return 'همین حالا';if($seconds<3600)return floor($seconds/60).' دقیقه پیش';if($seconds<86400)return floor($seconds/3600).' ساعت پیش';return floor($seconds/86400).' روز پیش';}
    private function allowedBranchIds(int $actor):array{$user=DB::table('users')->where('user_id',$actor)->whereNull('deleted_at')->first();if(!$user)throw new RuntimeException('کاربر معتبر نیست.');if(SiteAdminAccess::allows($user))$rows=DB::table('academy_branches')->whereNull('deleted_at')->get();elseif(($user['type']??'')==='branch')$rows=DB::table('academy_branches')->where('user_id',$actor)->whereNull('deleted_at')->get();else{$academies=array_merge(DB::table('academies')->where('user_id',$actor)->whereNull('deleted_at')->get(),DB::table('academies')->where('created_by',$actor)->whereNull('deleted_at')->get());$managed=DB::table('academy_branch_members')->join('academy_branch_member_roles','academy_branch_member_roles.member_id','=','academy_branch_members.member_id')->where('academy_branch_members.user_id',$actor)->whereIn('academy_branch_member_roles.role_id',[7,16])->whereNull('academy_branch_members.deleted_at')->whereNull('academy_branch_member_roles.deleted_at')->get();$academyIds=array_values(array_unique(array_merge(array_map(fn($academy)=>(int)$academy['academy_id'],$academies),array_map(fn($member)=>(int)$member['academy_id'],$managed))));$rows=$academyIds?DB::table('academy_branches')->whereIn('academy_id',$academyIds)->whereNull('deleted_at')->get():[];}return array_values(array_unique(array_map(fn($row)=>(int)$row['branch_id'],$rows)));}
}
