<?php

namespace Modules\Analytics\Services;

use Core\database\DB;
use RuntimeException;
use Modules\System\Services\SiteAdminAccess;

final class AdminAccountService
{
    private const IMAGE_MIME=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];
    private const DOCUMENT_MIME=['application/pdf'=>'pdf','image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','application/vnd.openxmlformats-officedocument.wordprocessingml.document'=>'docx'];

    public function data(int $actor): array
    {
        [$academy,$account]=$this->context($actor);$academyId=(int)$academy['academy_id'];$accountId=(int)$account['user_id'];$locale=locale();$branch=$this->branchContext($accountId);$isBranch=(bool)$branch;$isAcademy=($account['type']??'')==='academy';$isHuman=!$isBranch&&!$isAcademy;
        $managerId=(int)($academy['created_by']?:$actor);$manager=DB::table('users')->where('user_id',$managerId)->first();
        $address=DB::table('user_addresses')->where('user_id',$accountId)->whereNull('deleted_at')->orderBy('is_main','DESC')->first();
        $branches=$isBranch?[$branch]:($isAcademy?DB::table('academy_branches')->where('academy_id',$academyId)->whereNull('deleted_at')->get():[]);$branchIds=array_map(fn($x)=>(int)$x['branch_id'],$branches);
        $members=$branchIds?DB::table('academy_branch_members')->whereIn('branch_id',$branchIds)->where('status','active')->whereNull('deleted_at')->get():[];$memberIds=array_map(fn($x)=>(int)$x['member_id'],$members);
        $contracts=$memberIds?DB::table('academy_branch_member_contracts')->whereIn('member_id',$memberIds)->whereNull('deleted_at')->get():[];$teachers=array_unique(array_map(fn($x)=>(int)$x['member_id'],array_filter($contracts,fn($x)=>$x['type']==='teacher')));$staff=array_unique(array_map(fn($x)=>(int)$x['member_id'],$contracts));
        $students=array_filter($members,fn($x)=>!in_array((int)$x['member_id'],$staff,true));
        $avatar=$account['avatar_file_id']?$this->media((int)$account['avatar_file_id']):null;$cover=DB::table('media_files')->where('user_id',$accountId)->where('collection','cover')->whereNull('deleted_at')->orderBy('media_file_id','DESC')->first();
        $settings=$this->settings($accountId);$visibility=(string)($account['visibility']??'unlisted');
        return [
            'profile'=>['academyId'=>$academyId,'accountUserId'=>$accountId,'accountType'=>$isBranch?'branch':($isAcademy?'academy':'human'),'entityLabel'=>$isBranch?'شعبه':($isAcademy?'آموزشگاه':'کاربر'),'name'=>$isBranch?$this->tr('academy_branches',(int)$branch['branch_id'],'name',$locale,$this->tr('users',$accountId,'full_name',$locale,$account['username']??'شعبه')):($isAcademy?$this->tr('academies',$academyId,'title',$locale,$this->tr('users',$accountId,'full_name',$locale,'آموزشگاه '.$academyId)):$this->tr('users',$accountId,'full_name',$locale,$account['username']??('کاربر '.$accountId))),'type'=>$isBranch?'شعبه فیزیکی':($isAcademy?'آموزشگاه':'حساب شخصی'),'manager'=>$isHuman?'':$this->tr('users',$managerId,'full_name',$locale,$manager['username']??('کاربر '.$managerId)),'email'=>$account['email']??'','phone'=>$account['phone']??'','address'=>$address?$this->tr('user_addresses',(int)$address['address_id'],'address',$locale,''):'','founded'=>$account['birthday']??'','branches'=>count($branches),'students'=>count($students),'teachers'=>count($teachers),'avatarId'=>$avatar?(int)$avatar['media_file_id']:null,'coverId'=>$cover?(int)$cover['media_file_id']:null,'avatarUrl'=>$avatar?$this->url($avatar['path']):'','coverUrl'=>$cover?$this->url($cover['path']):'','shortIntro'=>$isBranch?$this->tr('academy_branches',(int)$branch['branch_id'],'short_description',$locale,$this->tr('users',$accountId,'short_description',$locale,'')):($isAcademy?$this->tr('academies',$academyId,'short_description',$locale,$this->tr('users',$accountId,'short_description',$locale,'')):$this->tr('users',$accountId,'short_description',$locale,'')),'biography'=>$isBranch?$this->tr('academy_branches',(int)$branch['branch_id'],'description',$locale,$this->tr('users',$accountId,'biography',$locale,'')):($isAcademy?$this->tr('academies',$academyId,'description',$locale,$this->tr('users',$accountId,'biography',$locale,'')):$this->tr('users',$accountId,'biography',$locale,'')),'privacy'=>['accountType'=>$isBranch?'branch':($isAcademy?'academy':'human'),'showPublicProfile'=>$visibility==='public','showBranches'=>$this->boolSetting($settings,'privacy_show_branches',true),'showTeachers'=>$this->boolSetting($settings,'privacy_show_teachers',true),'showContact'=>$this->boolSetting($settings,'privacy_show_contact',true),'showStats'=>$this->boolSetting($settings,'privacy_show_stats',false),'indexable'=>$this->boolSetting($settings,'privacy_indexable',$visibility==='public')]],
            'documents'=>$isAcademy?$this->documents($academyId,$locale):[],'devices'=>$this->devices($actor),'loginHistory'=>$this->loginHistory($actor),'securityAlerts'=>$this->securityAlerts($actor),'backup'=>$isAcademy?$this->lastBackup($academyId):null
        ];
    }

    public function saveProfile(int$actor,array$d):void
    {[$a,$u]=$this->context($actor);$aid=(int)$a['academy_id'];$uid=(int)$u['user_id'];$name=trim((string)($d['name']??''));if(!$name)throw new RuntimeException('نام حساب الزامی است.');$birthday=$this->date($d['founded']??null);DB::table('users')->where('user_id',$uid)->update(['email'=>$this->email($d['email']??null),'phone'=>$this->phone($d['phone']??null),'birthday'=>$birthday,'updated_by'=>$actor]);$this->setTr('users',$uid,'full_name',$name,$actor);$branch=$this->branchContext($uid);if($branch)$this->setTr('academy_branches',(int)$branch['branch_id'],'name',$name,$actor);elseif(($u['type']??'')==='academy')$this->setTr('academies',$aid,'title',$name,$actor);$addressText=trim((string)($d['address']??''));$address=DB::table('user_addresses')->where('user_id',$uid)->whereNull('deleted_at')->orderBy('is_main','DESC')->first();if(!$address)$addressId=DB::table('user_addresses')->insertGetId(['user_id'=>$uid,'country_id'=>1,'is_main'=>1,'created_by'=>$actor,'updated_by'=>$actor]);else$addressId=(int)$address['address_id'];$this->setTr('user_addresses',$addressId,'address',$addressText,$actor);}
    public function saveBio(int$actor,array$d):void{[$a,$u]=$this->context($actor);$uid=(int)$u['user_id'];$branch=$this->branchContext($uid);foreach(['short_description'=>'shortIntro','biography'=>'biography']as$f=>$k)$this->setTr('users',$uid,$f,trim((string)($d[$k]??'')),$actor);if($branch){$this->setTr('academy_branches',(int)$branch['branch_id'],'short_description',trim((string)($d['shortIntro']??'')),$actor);$this->setTr('academy_branches',(int)$branch['branch_id'],'description',trim((string)($d['biography']??'')),$actor);}elseif(($u['type']??'')==='academy'){foreach(['short_description'=>'shortIntro','description'=>'biography']as$f=>$k)$this->setTr('academies',(int)$a['academy_id'],$f,trim((string)($d[$k]??'')),$actor);}}
    public function savePrivacy(int$actor,array$d):void{[, $u]=$this->context($actor);$uid=(int)$u['user_id'];DB::table('users')->where('user_id',$uid)->update(['visibility'=>!empty($d['showPublicProfile'])?'public':'private','updated_by'=>$actor]);foreach(['privacy_show_branches'=>'showBranches','privacy_show_teachers'=>'showTeachers','privacy_show_contact'=>'showContact','privacy_show_stats'=>'showStats','privacy_indexable'=>'indexable']as$key=>$field)$this->setSetting($uid,$key,!empty($d[$field])?'1':'0',$actor);}
    public function saveSecurity(int$actor,array$d):void{[, $u]=$this->context($actor);$uid=(int)$u['user_id'];$values=['email'=>$this->email($d['email']??null),'phone'=>$this->phone($d['phone']??null),'updated_by'=>$actor];$password=(string)($d['password']??'');if($password!==''){if(strlen($password)<8)throw new RuntimeException('رمز عبور باید حداقل ۸ کاراکتر باشد.');if(!hash_equals($password,(string)($d['passwordConfirmation']??'')))throw new RuntimeException('تکرار رمز عبور مطابقت ندارد.');$values['password']=password_hash($password,PASSWORD_DEFAULT);}DB::table('users')->where('user_id',$uid)->update($values);if($password!=='')$this->securityEvent($actor,'password_changed','رمز عبور حساب آموزشگاه تغییر کرد.');}
    public function uploadMedia(int$actor,array$file,string$kind,array$meta=[]):array
    {[$a,$u]=$this->context($actor);$aid=(int)$a['academy_id'];$uid=(int)$u['user_id'];$allowed=$kind==='document'?self::DOCUMENT_MIME:self::IMAGE_MIME;if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('بارگذاری فایل کامل نشد.');$limit=$kind==='document'?20*1024*1024:8*1024*1024;if((int)$file['size']<=0||(int)$file['size']>$limit)throw new RuntimeException('حجم فایل بیش از حد مجاز است.');$mime=(new \finfo(FILEINFO_MIME_TYPE))->file((string)$file['tmp_name']);if(!isset($allowed[$mime]))throw new RuntimeException('نوع فایل مجاز نیست.');$ext=$allowed[$mime];$dir='storage/account-media/'.$uid.'/'.date('Y/m');$abs=base_path($dir);if(!is_dir($abs)&&!mkdir($abs,0775,true)&&!is_dir($abs))throw new RuntimeException('ایجاد پوشه فایل ناموفق بود.');$filename=bin2hex(random_bytes(16)).'.'.$ext;$path=$dir.'/'.$filename;if(!move_uploaded_file((string)$file['tmp_name'],base_path($path)))throw new RuntimeException('ذخیره فایل ناموفق بود.');$type=str_starts_with($mime,'image/')?'image':'document';$collection=$kind==='avatar'?'avatar':($kind==='cover'?'cover':'document');$branch=$this->branchContext($uid);$fileableType=$branch?'branch':(($u['type']??'')==='academy'?'academy':'user');$fileableId=$branch?(int)$branch['branch_id']:(($u['type']??'')==='academy'?$aid:$uid);$id=DB::table('media_files')->insertGetId(['user_id'=>$uid,'disk'=>$kind==='document'?'private':'public','directory'=>$dir,'filename'=>$filename,'extension'=>$ext,'mime_type'=>$mime,'type'=>$type,'collection'=>$collection,'path'=>$path,'original_filename'=>(string)$file['name'],'fileable_type'=>$fileableType,'fileable_id'=>$fileableId,'size'=>(int)$file['size'],'checksum'=>hash_file('sha256',base_path($path)),'visibility'=>$kind==='document'?'private':'public','created_by'=>$actor,'updated_by'=>$actor]);if($kind==='avatar')DB::table('users')->where('user_id',$uid)->update(['avatar_file_id'=>$id,'updated_by'=>$actor]);if(in_array($kind,['avatar','cover'],true))DB::table('media_files')->where('user_id',$uid)->where('collection',$collection)->where('media_file_id','!=',$id)->whereNull('deleted_at')->update(['deleted_at'=>date('Y-m-d H:i:s'),'deleted_by'=>$actor,'updated_by'=>$actor]);if($kind==='document')DB::table('academy_documents')->insert(['academy_id'=>$aid,'media_file_id'=>$id,'document_type'=>in_array($meta['documentType']??'',['license','identity','statute','tax','contract','certificate','other'],true)?$meta['documentType']:'other','document_number'=>trim((string)($meta['documentNumber']??''))?:null,'issued_at'=>$this->date($meta['issuedAt']??null),'expires_at'=>$this->date($meta['expiresAt']??null),'status'=>'pending','created_by'=>$actor,'updated_by'=>$actor]);return['id'=>$id,'url'=>$this->url($path)];}
    public function saveMediaMetadata(int$actor,int$id,array$data):void{[, $u]=$this->context($actor);$row=DB::table('media_files')->where('media_file_id',$id)->where('user_id',(int)$u['user_id'])->whereNull('deleted_at')->first();if(!$row)throw new RuntimeException('رسانه یافت نشد.');$title=trim((string)($data['title']??''));if($title==='')throw new RuntimeException('عنوان رسانه الزامی است.');foreach(['title','summary','description']as$field)$this->setTr('media_files',$id,$field,trim((string)($data[$field]??'')),$actor);}
    public function deleteMedia(int$actor,int$id):void{[, $u]=$this->context($actor);$uid=(int)$u['user_id'];$row=DB::table('media_files')->where('media_file_id',$id)->where('user_id',$uid)->whereNull('deleted_at')->first();if(!$row)throw new RuntimeException('فایل یافت نشد.');$now=date('Y-m-d H:i:s');DB::table('media_files')->where('media_file_id',$id)->update(['deleted_at'=>$now,'deleted_by'=>$actor,'updated_by'=>$actor]);DB::table('academy_documents')->where('media_file_id',$id)->whereNull('deleted_at')->update(['deleted_at'=>$now,'deleted_by'=>$actor]);if((int)($u['avatar_file_id']??0)===$id)DB::table('users')->where('user_id',$uid)->update(['avatar_file_id'=>null,'updated_by'=>$actor]);}
    public function downloadableMedia(int$actor,int$id):array{[$a]=$this->context($actor);$row=DB::table('media_files')->where('media_file_id',$id)->where('fileable_type','academy')->where('fileable_id',(int)$a['academy_id'])->whereNull('deleted_at')->first();if(!$row||!DB::table('academy_documents')->where('media_file_id',$id)->whereNull('deleted_at')->first())throw new RuntimeException('سند یافت نشد.');return['path'=>base_path($row['path']),'filename'=>$row['original_filename']?:$row['filename'],'mime'=>$row['mime_type']?:'application/octet-stream'];}
    public function endTrackingSession(int$actor,int$id):void{$r=DB::table('tracking_user_sessions')->where('tracking_user_session_id',$id)->where('user_id',$actor)->first();if(!$r)throw new RuntimeException('نشست یافت نشد.');DB::table('tracking_user_sessions')->where('session_id',(string)$r['session_id'])->where('user_id',$actor)->update(['status'=>'ended','ended_at'=>date('Y-m-d H:i:s'),'end_reason'=>'logout','auth_revoked_at'=>date('Y-m-d H:i:s.v'),'auth_revoked_by'=>$actor]);}

    private function context(int $actor):array{$current=DB::table('users')->where('user_id',$actor)->whereNull('deleted_at')->first();if(!$current)throw new RuntimeException('حساب کاربری یافت نشد.');$branch=$this->branchContext($actor);$academy=$branch?DB::table('academies')->where('academy_id',(int)$branch['academy_id'])->whereNull('deleted_at')->first():(DB::table('academies')->where('user_id',$actor)->whereNull('deleted_at')->first()?:DB::table('academies')->where('created_by',$actor)->whereNull('deleted_at')->orderBy('academy_id')->first());if(!$academy&&SiteAdminAccess::allows($current))$academy=DB::table('academies')->whereNull('deleted_at')->orderBy('academy_id')->first();return[$academy?:['academy_id'=>0,'created_by'=>$actor],$current];}
    private function branchContext(int$userId):?array{return DB::table('academy_branches')->where('user_id',$userId)->whereNull('deleted_at')->first();}
    private function documents(int$aid,string$locale):array{$rows=db()->prepare('SELECT d.*,m.* FROM academy_documents d JOIN media_files m ON m.media_file_id=d.media_file_id AND m.deleted_at IS NULL WHERE d.academy_id=? AND d.deleted_at IS NULL ORDER BY d.academy_document_id DESC');$rows->execute([$aid]);return array_map(fn($r)=>['id'=>(int)$r['media_file_id'],'documentId'=>(int)$r['academy_document_id'],'name'=>$r['original_filename']?:$r['filename'],'size'=>$this->size((int)$r['size']),'date'=>$r['created_at'],'type'=>$r['type'],'documentType'=>$r['document_type'],'number'=>$r['document_number'],'issuedAt'=>$r['issued_at'],'expiresAt'=>$r['expires_at'],'status'=>$r['status'],'url'=>'/analytics/admin-account/media/'.(int)$r['media_file_id'].'/download'],$rows->fetchAll());}
    private function devices(int$uid):array{$rows=DB::table('tracking_user_sessions')->where('user_id',$uid)->orderBy('last_heartbeat_at','DESC')->limit(20)->get();$sid=session_id();return array_map(fn($r)=>['id'=>(int)$r['tracking_user_session_id'],'name'=>trim(($r['browser']?:'مرورگر').' · '.($r['os']?:$r['platform']?:'دستگاه')),'location'=>trim(($r['city_name']?:'').' '.($r['country_code']?:''))?:'نامشخص','lastActive'=>$r['last_activity_at']?:$r['started_at'],'current'=>$r['session_id']===$sid,'ip'=>$r['ip_address']?:'—','status'=>$r['status']],$rows);}
    private function loginHistory(int$uid):array{$rows=DB::table('tracking_user_sessions')->where('user_id',$uid)->orderBy('started_at','DESC')->limit(30)->get();return array_map(fn($r)=>['id'=>(int)$r['tracking_user_session_id'],'action'=>'ورود','device'=>trim(($r['browser']?:'مرورگر').' · '.($r['os']?:'دستگاه')),'ip'=>$r['ip_address']?:'—','date'=>$r['started_at'],'ok'=>true],$rows);}
    private function securityAlerts(int$uid):array{$q=db()->prepare("SELECT * FROM tracking_user_events WHERE user_id=? AND event_name IN ('login_failed','password_changed','network_offline') ORDER BY occurred_at DESC LIMIT 30");$q->execute([$uid]);return array_map(fn($r)=>['id'=>(int)$r['tracking_user_event_id'],'level'=>$r['event_name']==='login_failed'?'danger':'info','title'=>$r['event_name']==='login_failed'?'تلاش ورود ناموفق':($r['event_name']==='password_changed'?'تغییر رمز عبور':'قطع اتصال شبکه'),'text'=>$r['event_label']?:'این رویداد توسط سامانه ثبت شده است.','date'=>$r['occurred_at']],$q->fetchAll());}
    private function settings(int$uid):array{$out=[];foreach(DB::table('z_user_settings')->where('user_id',$uid)->whereNull('deleted_at')->get()as$r)$out[$r['key']]=$r['value'];return$out;}
    private function setSetting(int$uid,string$key,string$value,int$actor):void{$r=DB::table('z_user_settings')->where('user_id',$uid)->where('`key`',$key)->first();$v=['value'=>$value,'type'=>'bool','visibility'=>'private','updated_by'=>$actor,'deleted_at'=>null,'deleted_by'=>null];if($r)DB::table('z_user_settings')->where('` user_setting_id`',(int)$r[' user_setting_id'])->update($v);else DB::table('z_user_settings')->insert(['user_id'=>$uid,'`key`'=>$key,'created_by'=>$actor]+$v);}
    private function boolSetting(array$s,string$k,bool$d):bool{return array_key_exists($k,$s)?in_array((string)$s[$k],['1','true','yes'],true):$d;}
    private function securityEvent(int$uid,string$name,string$label):void{$s=DB::table('tracking_user_sessions')->where('user_id',$uid)->orderBy('tracking_user_session_id','DESC')->first();if(!$s)return;$p=DB::table('tracking_user_page_views')->where('tracking_user_session_id',(int)$s['tracking_user_session_id'])->orderBy('tracking_user_page_view_id','DESC')->first();if(!$p)return;$sequence=(int)(db()->query('SELECT COALESCE(MAX(sequence_number),0)+1 FROM tracking_user_events WHERE page_view_id='.(int)$p['tracking_user_page_view_id'])->fetchColumn());$uuid=sprintf('%s-%s-4%s-%s%s-%s',bin2hex(random_bytes(4)),bin2hex(random_bytes(2)),substr(bin2hex(random_bytes(2)),1),dechex(random_int(8,11)),substr(bin2hex(random_bytes(2)),1),bin2hex(random_bytes(6)));DB::table('tracking_user_events')->insert(['event_uuid'=>$uuid,'tracking_user_session_id'=>(int)$s['tracking_user_session_id'],'user_id'=>$uid,'page_view_id'=>(int)$p['tracking_user_page_view_id'],'sequence_number'=>$sequence,'event_name'=>$name,'event_category'=>'security','event_action'=>$name,'event_label'=>$label,'occurred_at'=>date('Y-m-d H:i:s.v'),'client_timestamp_ms'=>(int)(microtime(true)*1000),'event_version'=>1,'source'=>'server','event_data'=>'{}','page_url'=>$p['page_url']]);}
    private function tr(string$t,int$id,string$f,string$l,string$d=''):string{$r=DB::table('translations')->where('table_name',$t)->where('table_id',$id)->where('field',$f)->where('locale',$l)->whereNull('deleted_at')->orderBy('translation_id','DESC')->first();if(!$r&&$l!=='fa')$r=DB::table('translations')->where('table_name',$t)->where('table_id',$id)->where('field',$f)->where('locale','fa')->whereNull('deleted_at')->orderBy('translation_id','DESC')->first();return(string)($r['value']??$d);}
    private function setTr(string$t,int$id,string$f,string$v,int$a):void{if(!\Core\translation\TranslationService::manager()->set($t,$id,$f,$v,locale()))throw new RuntimeException('ذخیره اطلاعات ترجمه‌شده ناموفق بود.');DB::table('translations')->where('table_name',$t)->where('table_id',$id)->where('field',$f)->where('locale',locale())->whereNull('deleted_at')->update(['updated_by'=>$a]);}
    private function media(int$id):?array{return DB::table('media_files')->where('media_file_id',$id)->whereNull('deleted_at')->first();}private function url(string$p):string{return preg_match('~^https?://~',$p)?$p:'/'.ltrim($p,'/');}private function size(int$b):string{return$b>=1048576?round($b/1048576,1).' مگابایت':max(1,round($b/1024)).' کیلوبایت';}
    private function email(mixed$v):?string{$v=strtolower(trim((string)$v));if($v!==''&&!filter_var($v,FILTER_VALIDATE_EMAIL))throw new RuntimeException('ایمیل معتبر نیست.');return$v?:null;}private function phone(mixed$v):?string{$v=preg_replace('/[^0-9+]/','',(string)$v);return$v?:null;}private function date(mixed$v):?string{$v=trim((string)$v);return preg_match('/^\d{4}-\d{2}-\d{2}$/',$v)?$v:null;}
    private function lastBackup(int$aid):?array{$r=DB::table('media_files')->where('fileable_type','academy_backup')->where('fileable_id',$aid)->whereNull('deleted_at')->orderBy('media_file_id','DESC')->first();return$r?['id'=>(int)$r['media_file_id'],'date'=>$r['created_at'],'size'=>$this->size((int)$r['size'])]:null;}
}
