<?php
namespace Modules\Analytics\Services;
use Core\database\DB;use RuntimeException;
class AdminSettingService{
 private const FONTS=['vazir'=>['وزیر','SornazVazirFa','SornazVazirEn'],'sahel'=>['ساحل','SornazSahelFa','SornazSahelEn'],'iran_yekan'=>['ایران‌یکان','SornazYekanFa','SornazYekanEn'],'iran_sansx'=>['ایران‌سنس X','SornazSansXFa','SornazSansXEn'],'kalameh'=>['کلمه','SornazKalamehFa','SornazKalamehEn'],'peyda'=>['پیدا','SornazPeyda','SornazPeyda']];
 public function get():array{$key=$this->fontKey($this->value('site_primary_font','vazir'));$scale=max(-2,min(2,(int)$this->value('site_font_size_scale',0)));$language=(string)$this->value('site_language','fa');if(!in_array($language,['fa','en'],true))$language='fa';$mode=(string)$this->value('site_theme_mode','light');if(!in_array($mode,['light','dark'],true))$mode='light';$theme=(string)$this->value('site_color_theme','indigo');if(!in_array($theme,['indigo','emerald','rose','amber'],true))$theme='indigo';$english=locale()==='en';$fonts=[];foreach(self::FONTS as$value=>$font)$fonts[]=['value'=>$value,'label'=>$font[0],'fontFamily'=>$font[$english?2:1].', Tahoma, sans-serif'];return['primaryFont'=>$key,'fontFamily'=>self::FONTS[$key][$english?2:1].', Tahoma, sans-serif','fontScale'=>$scale,'rootFontSize'=>(16+$scale).'px','digitStyle'=>$english?'en':'fa','language'=>$language,'themeMode'=>$mode,'colorTheme'=>$theme,'fonts'=>$fonts];}
 public function save(int$actor,array$data):array{if(array_key_exists('primaryFont',$data))$this->put('site_primary_font',$this->fontKey($data['primaryFont']),'string',$actor);if(array_key_exists('fontScale',$data)){$scale=(int)$data['fontScale'];if($scale < -2||$scale > 2)throw new RuntimeException('اندازه فونت انتخاب‌شده معتبر نیست.');$this->put('site_font_size_scale',$scale,'integer',$actor);}if(array_key_exists('language',$data)){$language=(string)$data['language'];if(!in_array($language,['fa','en'],true))throw new RuntimeException('زبان انتخاب‌شده معتبر نیست.');$this->put('site_language',$language,'string',$actor);}if(array_key_exists('themeMode',$data)){$mode=(string)$data['themeMode'];if(!in_array($mode,['light','dark'],true))throw new RuntimeException('حالت نمایش انتخاب‌شده معتبر نیست.');$this->put('site_theme_mode',$mode,'string',$actor);}if(array_key_exists('colorTheme',$data)){$theme=(string)$data['colorTheme'];if(!in_array($theme,['indigo','emerald','rose','amber'],true))throw new RuntimeException('تم رنگی انتخاب‌شده معتبر نیست.');$this->put('site_color_theme',$theme,'string',$actor);}return$this->get();}
 private function fontKey(mixed$value):string{$key=(string)$value;if($key==='vazirmatn')$key='vazir';$key=(string)preg_replace('/_(fa|en)$/','',$key);if(!isset(self::FONTS[$key]))throw new RuntimeException('فونت انتخاب‌شده معتبر نیست.');return$key;}
 private function value(string$key,mixed$default):mixed{$row=DB::table('z_settings')->where('`key`',$key)->where('is_active',1)->whereNull('deleted_at')->first();if(!$row)return$default;$value=json_decode((string)$row['value'],true);return json_last_error()===JSON_ERROR_NONE?$value:$default;}
 private function put(string$key,mixed$value,string$type,int$actor):void{$now=date('Y-m-d H:i:s');$row=DB::table('z_settings')->where('`key`',$key)->first();$values=['`group`'=>'appearance','type'=>$type,'value'=>json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'is_active'=>1,'updated_at'=>$now,'updated_by'=>$actor,'deleted_at'=>null,'deleted_by'=>null];if($row)DB::table('z_settings')->where('setting_id',(int)$row['setting_id'])->update($values);else DB::table('z_settings')->insert(['`key`'=>$key,'created_at'=>$now,'created_by'=>$actor]+$values);}
}
