<?php
namespace Modules\Analytics\Services;
use Core\database\DB;use RuntimeException;
class AdminUserAccessService{
 public function index(array$f):array{$page=max(1,(int)($f['page']??1));$per=in_array((int)($f['perPage']??20),[10,20,30,50,100],true)?(int)$f['perPage']:20;$where=['u.deleted_at IS NULL'];$bind=[];if(!empty($f['branchId'])){$branchId=(int)$f['branchId'];if($branchId<1)throw new RuntimeException('شعبه انتخاب‌شده معتبر نیست.');$where[]='(EXISTS(SELECT 1 FROM academy_branch_members abm WHERE abm.user_id=u.user_id AND abm.branch_id=? AND abm.deleted_at IS NULL) OR EXISTS(SELECT 1 FROM academy_branches ab WHERE ab.user_id=u.user_id AND ab.branch_id=? AND ab.deleted_at IS NULL))';array_push($bind,$branchId,$branchId);}if(!empty($f['status'])){$where[]='u.status=?';$bind[]=$f['status'];}if(!empty($f['search'])){$q='%'.trim((string)$f['search']).'%';$where[]="(u.username LIKE ? OR u.email LIKE ? OR u.phone LIKE ? OR EXISTS(SELECT 1 FROM translations t WHERE t.table_name='users' AND t.table_id=u.user_id AND t.field='full_name' AND t.deleted_at IS NULL AND t.value LIKE ?))";array_push($bind,$q,$q,$q,$q);} $w=implode(' AND ',$where);$total=(int)$this->query("SELECT COUNT(*) FROM users u WHERE $w",$bind,true);$offset=($page-1)*$per;$rows=$this->query("SELECT u.* FROM users u WHERE $w ORDER BY u.user_id DESC LIMIT $offset,$per",$bind);return['users'=>array_map(fn($u)=>$this->mapUser($u),$rows),'roles'=>$this->roles(),'permissions'=>$this->permissions(),'branches'=>$this->branches(),'total'=>$total,'page'=>$page,'perPage'=>$per];}
 public function save(int$actor,int$id,array$data):void{if($id===1||$id===$actor)throw new RuntimeException('برای جلوگیری از قطع دسترسی مدیریت، مجوزهای این حساب از این صفحه قابل تغییر نیست.');$user=DB::table('users')->where('user_id',$id)->whereNull('deleted_at')->first();if(!$user)throw new RuntimeException('کاربر یافت نشد.');$validRoles=array_column($this->roles(),'id');$validPerms=array_column($this->permissions(),'id');$roles=array_values(array_unique(array_map('intval',(array)($data['roleIds']??[]))));$perms=array_values(array_unique(array_map('intval',(array)($data['permissionIds']??[]))));if(array_diff($roles,$validRoles)||array_diff($perms,$validPerms))throw new RuntimeException('نقش یا مجوز انتخاب‌شده معتبر نیست.');transaction(function()use($actor,$id,$roles,$perms){$this->sync('user_roles','user_role_id','role_id',$id,$roles,$actor,true);$this->sync('user_permissions','user_permission_id','permission_id',$id,$perms,$actor,false);});}
 private function sync(string$table,string$key,string$itemKey,int$userId,array$selected,int$actor,bool$main):void{$now=date('Y-m-d H:i:s');$rows=DB::table($table)->where('user_id',$userId)->get();foreach($rows as$r){$item=(int)$r[$itemKey];if(in_array($item,$selected,true)){$v=['deleted_at'=>null,'deleted_by'=>null,'updated_at'=>$now,'updated_by'=>$actor];if($main)$v['is_main']=$item===(int)($selected[0]??0)?1:0;DB::table($table)->where($key,(int)$r[$key])->update($v);}elseif($r['deleted_at']===null)DB::table($table)->where($key,(int)$r[$key])->update(['deleted_at'=>$now,'deleted_by'=>$actor]);}$known=array_map(fn($r)=>(int)$r[$itemKey],$rows);foreach(array_diff($selected,$known)as$item){$v=['user_id'=>$userId,$itemKey=>$item,'created_at'=>$now,'created_by'=>$actor,'updated_at'=>$now,'updated_by'=>$actor];if($main){$v['is_main']=$item===(int)($selected[0]??0)?1:0;$v['granted_by']=$actor;$v['granted_at']=$now;}DB::table($table)->insert($v);}}
 private function roles():array{$out=[];foreach(DB::table('access_system_roles')->whereNull('deleted_at')->orderBy('sort_order')->get()as$r)$out[]=['id'=>(int)$r['role_id'],'name'=>$r['name'],'title'=>$this->title('access_system_roles',(int)$r['role_id'],$r['name']),'color'=>$r['color']?:'#64748b'];return$out;}
 private function permissions():array{$out=[];foreach(DB::table('access_system_permissions')->whereNull('deleted_at')->orderBy('group_name')->orderBy('name')->get()as$p)$out[]=['id'=>(int)$p['permission_id'],'name'=>$p['name'],'title'=>$this->title('access_system_permissions',(int)$p['permission_id'],$p['name']),'group'=>$p['group_name']?:'other'];return$out;}
 private function branches():array{$rows=$this->query("SELECT b.branch_id,b.academy_id,COALESCE((SELECT value FROM translations WHERE table_name='academy_branches' AND table_id=b.branch_id AND field='name' AND locale=? AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),CONCAT('شعبه ',b.branch_id)) name,COALESCE((SELECT value FROM translations WHERE table_name='academies' AND table_id=b.academy_id AND field='name' AND locale=? AND deleted_at IS NULL ORDER BY translation_id DESC LIMIT 1),CONCAT('آموزشگاه ',b.academy_id)) academy_name FROM academy_branches b WHERE b.deleted_at IS NULL ORDER BY academy_name,name",[locale(),locale()]);return array_map(fn($b)=>['id'=>(int)$b['branch_id'],'name'=>$b['name'],'academyName'=>$b['academy_name']],$rows);}
 private function mapUser(array$u):array{$id=(int)$u['user_id'];$roles=[];foreach($this->query('SELECT r.role_id,r.name,r.color,ur.is_main FROM user_roles ur JOIN access_system_roles r ON r.role_id=ur.role_id AND r.deleted_at IS NULL WHERE ur.user_id=? AND ur.deleted_at IS NULL ORDER BY ur.is_main DESC',[$id])as$r)$roles[]=['id'=>(int)$r['role_id'],'name'=>$r['name'],'title'=>$this->title('access_system_roles',(int)$r['role_id'],$r['name']),'color'=>$r['color']?:'#64748b','main'=>(bool)$r['is_main']];$permissions=[];foreach($this->query('SELECT p.permission_id,p.name,p.group_name FROM user_permissions up JOIN access_system_permissions p ON p.permission_id=up.permission_id AND p.deleted_at IS NULL WHERE up.user_id=? AND up.deleted_at IS NULL AND (up.expires_at IS NULL OR up.expires_at>NOW())',[$id])as$p)$permissions[]=['id'=>(int)$p['permission_id'],'name'=>$p['name'],'title'=>$this->title('access_system_permissions',(int)$p['permission_id'],$p['name']),'group'=>$p['group_name']?:'other'];return['id'=>$id,'name'=>$this->title('users',$id,$u['username']?:('کاربر '.$id),'full_name'),'username'=>$u['username'],'email'=>$u['email'],'phone'=>$u['phone'],'type'=>$u['type'],'status'=>$u['status'],'lastLogin'=>$u['last_login_at'],'roles'=>$roles,'permissions'=>$permissions];}
 private function title(string$table,int$id,string$fallback,string$field='title'):string{$translationTable=in_array($table,['access_system_roles','access_system_permissions'],true)?'f_translations':'translations';$t=DB::table($translationTable)->where('table_name',$table)->where('table_id',$id)->where('locale',locale())->where('field',$field)->whereNull('deleted_at')->first();return(string)($t['value']??$fallback);}
 private function query(string$sql,array$bind=[],bool$scalar=false):mixed{$s=db()->prepare($sql);$s->execute($bind);return$scalar?$s->fetchColumn():$s->fetchAll();}
}
