<?php
namespace Modules\Analytics\Services;
use Core\database\DB;
use RuntimeException;
class AdminCommentService
{
 public function index(array$f):array{$page=max(1,(int)($f['page']??1));$per=in_array((int)($f['perPage']??20),[10,20,30,50,100],true)?(int)$f['perPage']:20;$where=['c.deleted_at IS NULL'];$b=[];if(!empty($f['status'])){$where[]='c.status=?';$b[]=$f['status'];}if(!empty($f['post'])){$where[]='c.post_id=?';$b[]=(int)$f['post'];}if(!empty($f['search'])){$q='%'.trim((string)$f['search']).'%';$where[]="(c.author LIKE ? OR c.author_email LIKE ? OR EXISTS(SELECT 1 FROM translations t WHERE t.table_name='comments' AND t.table_id=c.comment_id AND t.field='content' AND t.deleted_at IS NULL AND t.value LIKE ?))";array_push($b,$q,$q,$q);}$w=implode(' AND ',$where);$total=$this->query("SELECT COUNT(*) FROM comments c WHERE $w",$b,true);$offset=($page-1)*$per;$rows=$this->query("SELECT c.*,u.username FROM comments c LEFT JOIN users u ON u.user_id=c.user_id WHERE $w ORDER BY c.comment_id DESC LIMIT $offset,$per",$b);$counts=[];foreach($this->query('SELECT status,COUNT(*) total FROM comments WHERE deleted_at IS NULL GROUP BY status')as$r)$counts[$r['status']]=(int)$r['total'];$posts=[];foreach(DB::table('posts')->whereNull('deleted_at')->orderBy('post_id','DESC')->get()as$p){$t=DB::table('translations')->where('table_name','posts')->where('table_id',(int)$p['post_id'])->where('locale','fa')->where('field','title')->whereNull('deleted_at')->first();$posts[]=['id'=>(int)$p['post_id'],'title'=>$t['value']??('نوشته '.$p['post_id'])];}return['comments'=>array_map(fn($r)=>$this->map($r),$rows),'posts'=>$posts,'total'=>(int)$total,'page'=>$page,'perPage'=>$per,'statusCounts'=>$counts];}
 public function update(int$a,int$id,array$d):void{$r=$this->find($id);$status=in_array($d['status']??'',['pending','approved','rejected'],true)?$d['status']:$r['status'];$content=trim((string)($d['content']??$this->content($r)));if($content==='')throw new RuntimeException('متن دیدگاه الزامی است.');$now=date('Y-m-d H:i:s');DB::table('comments')->where('comment_id',$id)->update(['status'=>$status,'approved_at'=>$status==='approved'?$now:null,'approved_by'=>$status==='approved'?$a:null,'updated_at'=>$now,'updated_by'=>$a]);$this->setContent($id,$content,$a);}
 public function reply(int$a,int$id,array$d):int{$p=$this->find($id);$content=trim((string)($d['content']??''));if($content==='')throw new RuntimeException('متن پاسخ الزامی است.');$now=date('Y-m-d H:i:s');$new=(int)db()->query('SELECT COALESCE(MAX(comment_id),0)+1 FROM comments')->fetchColumn();DB::table('comments')->insert(['comment_id'=>$new,'post_id'=>(int)$p['post_id'],'user_id'=>$a,'author'=>(string)(auth()->user()['username']??'مدیر سایت'),'parent'=>$id,'has_response'=>0,'status'=>'approved','approved_at'=>$now,'approved_by'=>$a,'created_at'=>$now,'created_by'=>$a,'updated_at'=>$now,'updated_by'=>$a]);DB::table('comments')->where('comment_id',$id)->update(['has_response'=>1,'updated_at'=>$now,'updated_by'=>$a]);$this->setContent($new,$content,$a);return$new;}
 public function delete(int$a,int$id):void{$this->find($id);$now=date('Y-m-d H:i:s');DB::table('comments')->where('comment_id',$id)->update(['deleted_at'=>$now,'deleted_by'=>$a,'updated_at'=>$now,'updated_by'=>$a]);DB::table('translations')->where('table_name','comments')->where('table_id',$id)->whereNull('deleted_at')->update(['deleted_at'=>$now,'deleted_by'=>$a]);}
 private function find(int$id):array{$r=DB::table('comments')->where('comment_id',$id)->whereNull('deleted_at')->first();if(!$r)throw new RuntimeException('دیدگاه یافت نشد.');return$r;}
 private function map(array$r):array{$id=(int)$r['comment_id'];$p=DB::table('translations')->where('table_name','posts')->where('table_id',(int)$r['post_id'])->where('locale','fa')->where('field','title')->whereNull('deleted_at')->first();$name='';if(!empty($r['user_id'])){$t=DB::table('translations')->where('table_name','users')->where('table_id',(int)$r['user_id'])->where('locale','fa')->where('field','full_name')->whereNull('deleted_at')->first();$name=$t['value']??$r['username']??'';}return['id'=>$id,'postId'=>(int)$r['post_id'],'postTitle'=>$p['value']??('نوشته '.$r['post_id']),'author'=>$name?:($r['author']??'مهمان'),'email'=>$r['author_email']??'','content'=>$this->content($r),'parentId'=>!empty($r['parent'])?(int)$r['parent']:null,'status'=>$r['status']?:'pending','ip'=>$r['author_ip']??'','createdAt'=>$r['created_at']??null];}
 private function content(array$r):string{$t=DB::table('translations')->where('table_name','comments')->where('table_id',(int)$r['comment_id'])->where('field','content')->whereNull('deleted_at')->first();return(string)($t['value']??'');}
 private function setContent(int$id,string$c,int$a):void{$t=DB::table('translations')->where('table_name','comments')->where('table_id',$id)->where('locale','fa')->where('field','content')->first();$v=['value'=>$c,'version'=>1,'updated_by'=>$a,'deleted_at'=>null,'deleted_by'=>null];if($t)DB::table('translations')->where('translation_id',(int)$t['translation_id'])->update($v);else DB::table('translations')->insert(['table_name'=>'comments','table_id'=>$id,'locale'=>'fa','field'=>'content','created_by'=>$a]+$v);}
 private function query(string$s,array$b=[],bool$scalar=false):mixed{$q=db()->prepare($s);$q->execute($b);return$scalar?$q->fetchColumn():$q->fetchAll();}
}
