<?php
namespace Modules\Analytics\Services;
use Core\database\DB;use RuntimeException;
class SitePageContentService{
private const PAGES=[
['id'=>'home','title'=>'خانه','route'=>'/'],['id'=>'articles','title'=>'مقاله‌های آموزشی','route'=>'/analytics/articles'],['id'=>'article-details','title'=>'نمایش مقاله','route'=>'/analytics/article-details'],['id'=>'academies','title'=>'آموزشگاه‌ها','route'=>'/academy/academies'],['id'=>'users','title'=>'کاربران','route'=>'/users'],['id'=>'about-us','title'=>'درباره ما','route'=>'/page/about-us'],['id'=>'contact-us','title'=>'تماس با ما','route'=>'/page/contact-us'],['id'=>'login','title'=>'ورود','route'=>'/system/login'],['id'=>'register','title'=>'ثبت‌نام','route'=>'/system/register'],['id'=>'forgot-password','title'=>'فراموشی رمز عبور','route'=>'/system/forgot-password']];
public function pages():array{$rows=DB::table('f_settings')->where('table_name','site_page_content')->whereNull('deleted_at')->get();$counts=[];foreach($rows as$r){$p=(string)$r['page'];$kind=(string)($r['status']??'text');$counts[$p][$kind]=($counts[$p][$kind]??0)+1;}$firstPost=DB::table('posts')->where('status','published')->whereNull('deleted_at')->orderBy('post_id','ASC')->first();return array_map(function($p)use($counts,$firstPost){if($p['id']==='article-details')$p['route']=$firstPost?'/analytics/article-details?id='.(int)$firstPost['post_id']:'/analytics/articles';return$p+['texts'=>$counts[$p['id']]['text']??0,'images'=>$counts[$p['id']]['image']??0,'icons'=>$counts[$p['id']]['icon']??0];},self::PAGES);}
public function content(string$page,string$locale):array{$page=$this->validPage($page);$locale=in_array($locale,['fa','en'],true)?$locale:'fa';$out=[];foreach(DB::table('f_settings')->where('table_name','site_page_content')->where('page',$page)->whereNull('deleted_at')->get()as$r){$item=['key'=>$r['variable_name'],'kind'=>$r['status'],'value'=>$r['status']==='image'?($r['source']??''):($r['status']==='icon'?($r['icon']??''):($r['value']??''))];if($r['status']==='text'){$values=[];foreach(DB::table('f_translations')->where('table_name','f_settings')->where('table_id',(int)$r['setting_id'])->where('field','value')->whereNull('deleted_at')->get()as$tr)$values[$tr['locale']]=$tr['value'];$item['fa']=$values['fa']??'';$item['en']=$values['en']??'';$item['value']=$values[$locale]??$values['fa']??'';} $out[]=$item;}return$out;}
public function save(int$actor,array$d):void{$page=$this->validPage((string)($d['page']??''));$kind=in_array($d['kind']??'',['text','image','icon'],true)?$d['kind']:throw new RuntimeException('نوع محتوا معتبر نیست.');$key=trim((string)($d['key']??''));if(!preg_match('/^site\.page\.[a-z0-9-]+\.(text|image|icon)\.[a-z0-9]+$/',$key))throw new RuntimeException('کلید محتوا معتبر نیست.');$row=DB::table('f_settings')->where('variable_name',$key)->first();$base=['page'=>$page,'table_name'=>'site_page_content','status'=>$kind,'updated_by'=>$actor,'deleted_at'=>null,'deleted_by'=>null];if($kind==='image')$base['source']=trim((string)($d['value']??''));elseif($kind==='icon')$base['icon']=trim((string)($d['value']??''));else$base['value']=null;if($row){$id=(int)$row['setting_id'];DB::table('f_settings')->where('setting_id',$id)->update($base);}else$id=(int)DB::table('f_settings')->insertGetId(['variable_name'=>$key,'created_by'=>$actor]+$base);if($kind==='text')foreach(['fa','en']as$locale){$value=trim((string)($d[$locale]??''));if($value==='')throw new RuntimeException('متن فارسی و انگلیسی الزامی است.');$tr=DB::table('f_translations')->where('table_name','f_settings')->where('table_id',$id)->where('field','value')->where('locale',$locale)->first();$v=['value'=>$value,'version'=>1,'updated_by'=>$actor,'deleted_at'=>null,'deleted_by'=>null];if($tr)DB::table('f_translations')->where('translation_id',(int)$tr['translation_id'])->update($v);else DB::table('f_translations')->insert(['table_name'=>'f_settings','table_id'=>$id,'field'=>'value','locale'=>$locale,'created_by'=>$actor]+$v);}}
private function validPage(string$page):string{foreach(self::PAGES as$p)if($p['id']===$page)return$page;throw new RuntimeException('برگه معتبر نیست.');}}
