<?php
// Reviewed CLI-only retention manifest. Every table is explicit; unknown tables abort.
// 0 clears activity; 1 retains reference data; predicates retain administrator content.
return [
    "f_access_system_permissions" => "1",
    "f_access_system_role_permissions" => "1",
    "f_access_system_roles" => "1",
    "f_access_system_setting_permissions" => "1",
    "f_article_comment_receipts" => "0",
    "f_auth_rate_limits" => "0",
    "f_auth_remember_tokens" => "0",
    "f_categories" => "1",
    "f_comments" => "1",
    "f_conversation_members" => "0",
    "f_conversation_message_reactions" => "0",
    "f_conversation_messages" => "0",
    "f_conversations" => "0",
    "f_financial_system_accounts" => "0",
    "f_financial_system_currency" => "1",
    "f_financial_system_discounts" => "0",
    "f_financial_system_ledger_entries" => "0",
    "f_financial_system_payments" => "0",
    "f_financial_system_refunds" => "0",
    "f_financial_system_transactions" => "0",
    "f_legacy_settings" => "1",
    "f_media_files" => "user_id=1 OR media_file_id IN (SELECT cover_media_id FROM f_posts WHERE cover_media_id IS NOT NULL)",
    "f_posts" => "1",
    "f_public_ratings" => "0",
    "f_settings" => "1",
    "f_social_account_settings" => "user_id=1",
    "f_social_bookmarks" => "0",
    "f_social_comment_likes" => "0",
    "f_social_comments" => "0",
    "f_social_follows" => "0",
    "f_social_highlight_stories" => "0",
    "f_social_highlights" => "0",
    "f_social_media" => "0",
    "f_social_notifications" => "0",
    "f_social_posts" => "0",
    "f_social_profiles" => "user_id=1",
    "f_social_reactions" => "0",
    "f_social_story_mentions" => "0",
    "f_timezone" => "1",
    "f_tracking_ingestion_batches" => "0",
    "f_tracking_user_activity_intervals" => "0",
    "f_tracking_user_consents" => "0",
    "f_tracking_user_content_engagements" => "0",
    "f_tracking_user_events" => "0",
    "f_tracking_user_page_views" => "0",
    "f_tracking_user_sessions" => "0",
    "f_translations" => "translations",
    "f_user_addresses" => "user_id=1",
    "f_user_availabilities" => "user_id=1 AND member_id IS NULL",
    "f_user_awards" => "user_id=1",
    "f_user_badges" => "user_id=1",
    "f_user_certificates" => "user_id=1",
    "f_user_contacts" => "user_id=1",
    "f_user_educations" => "user_id=1",
    "f_user_events" => "user_id=1",
    "f_user_experiences" => "user_id=1",
    "f_user_merges" => "0",
    "f_user_messages" => "0",
    "f_user_permissions" => "user_id=1",
    "f_user_point_rules" => "academy_id IS NULL AND branch_id IS NULL",
    "f_user_points" => "0",
    "f_user_poll_options" => "0",
    "f_user_poll_votes" => "0",
    "f_user_polls" => "0",
    "f_user_profiles" => "user_id=1",
    "f_user_publications" => "user_id=1",
    "f_user_referrals" => "0",
    "f_user_roles" => "user_id=1",
    "f_user_sessions" => "0",
    "f_user_settings" => "user_id=1",
    "f_users" => "user_id=1",
    "f_verification_levels" => "1",
    "f_world_iran_counties" => "1",
    "f_world_iran_provinces" => "1",
    "p_academies" => "0",
    "p_academy_branch_bookings" => "0",
    "p_academy_branch_classroom_assets" => "0",
    "p_academy_branch_classrooms" => "0",
    "p_academy_branch_course_term_enrollments" => "0",
    "p_academy_branch_course_term_invoice_installments" => "0",
    "p_academy_branch_course_term_invoices" => "0",
    "p_academy_branch_course_term_schedule_skips" => "0",
    "p_academy_branch_course_term_session_attendances" => "0",
    "p_academy_branch_course_term_sessions" => "0",
    "p_academy_branch_course_term_waiting_list" => "0",
    "p_academy_branch_course_terms" => "0",
    "p_academy_branch_courses" => "0",
    "p_academy_branch_member_contracts" => "0",
    "p_academy_branch_member_permissions" => "0",
    "p_academy_branch_member_roles" => "0",
    "p_academy_branch_members" => "0",
    "p_academy_branch_scheduling_rules" => "0",
    "p_academy_branch_types" => "1",
    "p_academy_branches" => "0",
    "p_academy_documents" => "0",
    "p_academy_national_holiday_settings" => "0",
    "p_academy_subscription_payments" => "0",
    "p_academy_subscription_periods" => "0",
    "p_classroom_types" => "academy_id IS NULL AND branch_id IS NULL",
    "p_creator_course_details" => "course_id IN (SELECT id FROM p_creator_courses WHERE owner_id=1)",
    "p_creator_course_lessons" => "course_id IN (SELECT id FROM p_creator_courses WHERE owner_id=1) AND post_id IN (SELECT post_id FROM f_posts)",
    "p_creator_course_media" => "course_id IN (SELECT id FROM p_creator_courses WHERE owner_id=1)",
    "p_creator_course_orders" => "0",
    "p_creator_course_questions" => "0",
    "p_creator_course_reactions" => "0",
    "p_creator_course_reports" => "0",
    "p_creator_course_reviews" => "0",
    "p_creator_course_schedules" => "0",
    "p_creator_courses" => "owner_id=1",
    "p_creator_lesson_access" => "0",
    "p_instruments" => "1",
    "p_lessons" => "1",
    "p_levels" => "1",
    "p_music_sheet_bookmarks" => "0",
    "p_music_sheets" => "owner_id=1",
    "p_settings" => "1",
    "p_social_lesson_progress" => "0",
    "p_translations" => "translations",
    "p_user_instruments" => "user_id=1",
    "p_user_lessons" => "user_id=1",
];
