<?php

use Core\router\Router;
use Modules\Academy\Controllers\Web\AcademyController;
use Modules\Academy\Controllers\Web\AcademyRegistrationController;
use Modules\Analytics\Controllers\Web\AnalyticsController;
use Modules\Academy\Controllers\Web\AcademyBranchController;
use Modules\Academy\Controllers\Web\AcademyClassroomController;
use Modules\Academy\Controllers\Web\AcademyBranchOfferingController;
use Modules\Academy\Controllers\Web\AcademyCourseController;
use Modules\Academy\Controllers\Web\AcademyTermController;
use Modules\Academy\Controllers\Web\AcademyTermAvailabilityController;
use Modules\Academy\Controllers\Web\AcademyClassScheduleController;
use Modules\Academy\Controllers\Web\AcademyWeeklyScheduleBoundsController;
use Modules\Academy\Controllers\Web\NationalHolidayController;
use Modules\Academy\Controllers\Web\ZarinpalPaymentController;
use Modules\Academy\Controllers\Web\AcademySubscriptionController;

Router::get('/academy/academy', [AnalyticsController::class, 'academy']);
Router::get('/academy/academies', [AcademyRegistrationController::class, 'index']);
Router::get('/academy/academy-enroll', [AnalyticsController::class, 'academyEnroll'])->middleware('auth');
Router::post('/academy/academy-enroll', [AnalyticsController::class, 'academyEnrollStore'])->middleware(['auth','csrf']);
Router::get('/academy/send-academy-request', [AcademyRegistrationController::class, 'create']);
Router::post('/academy/send-academy-request', [AcademyRegistrationController::class, 'store']);
Router::post('/academy/send-academy-request/send-otp', [AcademyRegistrationController::class, 'sendOtp']);
Router::get('/academy/register-main-branch', [AcademyRegistrationController::class, 'createMainBranch']);
Router::post('/academy/register-main-branch', [AcademyRegistrationController::class, 'storeMainBranch']);
Router::post('/academy/register-main-branch/send-otp', [AcademyRegistrationController::class, 'sendMainBranchOtp']);
Router::post('/academy/_test/seed-sample-academies', [AcademyRegistrationController::class, 'seedSamples'])->middleware(['site-admin', 'csrf']);
Router::post('/academy/_test/delete-sample-academies', [AcademyRegistrationController::class, 'deleteSamples'])->middleware(['site-admin', 'csrf']);
Router::post('/academy/_test/seed-branch-network', [AcademyRegistrationController::class, 'seedBranchNetwork'])->middleware(['site-admin', 'csrf']);
Router::post('/academy/_test/delete-branch-network', [AcademyRegistrationController::class, 'deleteBranchNetwork'])->middleware(['site-admin', 'csrf']);
Router::get('/academy/admin/branches', [AcademyBranchController::class, 'index'])->middleware('academy-panel');
Router::get('/academy/admin/branches/realtime-version', [AcademyBranchController::class, 'realtimeVersion'])->middleware('academy-panel');
Router::get('/academy/admin/branches/registration-form', [AcademyRegistrationController::class, 'createAdminBranchDialog'])->middleware('academy-panel');
Router::post('/academy/admin/branches/registration/send-otp', [AcademyRegistrationController::class, 'sendAdminBranchOtp'])->middleware(['academy-panel', 'csrf']);
Router::post('/academy/admin/branches/registration', [AcademyRegistrationController::class, 'storeAdminBranch'])->middleware(['academy-panel', 'csrf']);
Router::post('/academy/admin/branches', [AcademyBranchController::class, 'store'])->middleware(['academy-panel', 'csrf']);
Router::post('/academy/admin/branches/types', [AcademyBranchController::class, 'storeType'])->middleware(['academy-panel', 'csrf']);
Router::post('/academy/admin/branch-types/{id}/update', [AcademyBranchController::class, 'updateType'])->middleware(['site-admin', 'csrf']);
Router::post('/academy/admin/branch-types/{id}/delete', [AcademyBranchController::class, 'deleteType'])->middleware(['site-admin', 'csrf']);
Router::post('/academy/admin/branches/{id}/update', [AcademyBranchController::class, 'update'])->middleware(['academy-panel', 'csrf']);
Router::post('/academy/admin/branches/{id}/status', [AcademyBranchController::class, 'cycleStatus'])->middleware(['academy-panel', 'csrf']);
Router::post('/academy/admin/branches/{id}/delete', [AcademyBranchController::class, 'destroy'])->middleware(['academy-panel', 'csrf']);
Router::post('/academy/admin/members', [AcademyBranchController::class, 'storeMember'])->middleware(['academy-panel', 'csrf']);
Router::get('/academy/admin/members/realtime-version', [AcademyBranchController::class, 'staffRealtimeVersion'])->middleware('academy-panel');
Router::get('/academy/admin/members/data', [AcademyBranchController::class, 'staffIndex'])->middleware('academy-panel');
Router::post('/academy/admin/members/{id}/update', [AcademyBranchController::class, 'updateMember'])->middleware(['academy-panel', 'csrf']);
Router::post('/academy/admin/members/{id}/status', [AcademyBranchController::class, 'cycleMemberStatus'])->middleware(['academy-panel', 'csrf']);
Router::post('/academy/admin/members/{id}/delete', [AcademyBranchController::class, 'deleteMember'])->middleware(['academy-panel', 'csrf']);
Router::get('/academy/admin/classrooms', [AcademyClassroomController::class, 'index'])->middleware('academy-panel');
Router::get('/academy/admin/classrooms/realtime-version', [AcademyClassroomController::class, 'classroomsRealtimeVersion'])->middleware('academy-panel');
Router::post('/academy/admin/classrooms', [AcademyClassroomController::class, 'store'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/classrooms/{id}/update', [AcademyClassroomController::class, 'update'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/classrooms/{id}/delete', [AcademyClassroomController::class, 'delete'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/classrooms/{id}/status', [AcademyClassroomController::class, 'cycleRoomStatus'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/classroom-types', [AcademyClassroomController::class, 'storeType'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/classroom-types/from-classroom', [AcademyClassroomController::class, 'storeTypeFromClassroom'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/classroom-types/{id}/update', [AcademyClassroomController::class, 'updateType'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/classroom-types/{id}/delete', [AcademyClassroomController::class, 'deleteType'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/classroom-types/{id}/status', [AcademyClassroomController::class, 'cycleTypeStatus'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/classroom-type-categories', [AcademyClassroomController::class, 'storeTypeCategory'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/classroom-type-categories/{value}/update', [AcademyClassroomController::class, 'updateTypeCategory'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/classroom-type-categories/{value}/delete', [AcademyClassroomController::class, 'deleteTypeCategory'])->middleware(['academy-panel','csrf']);
Router::get('/academy/admin/classroom-types/realtime-version', [AcademyClassroomController::class, 'realtimeVersion'])->middleware('academy-panel');
Router::get('/academy/admin/branch-offerings', [AcademyBranchOfferingController::class, 'index'])->middleware('academy-panel');
Router::get('/academy/admin/member-schedules', [AcademyBranchController::class, 'memberSchedules'])->middleware('academy-panel');
Router::post('/academy/admin/member-schedules', [AcademyBranchController::class, 'storeMemberSchedule'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/member-schedules/{id}/update', [AcademyBranchController::class, 'updateMemberSchedule'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/member-schedules/{id}/delete', [AcademyBranchController::class, 'deleteMemberSchedule'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/member-schedules/{id}/status', [AcademyBranchController::class, 'cycleMemberScheduleStatus'])->middleware(['academy-panel','csrf']);
Router::get('/academy/admin/availability-exceptions', [AcademyBranchController::class, 'availabilityExceptions'])->middleware('academy-panel');
Router::post('/academy/admin/availability-exceptions', [AcademyBranchController::class, 'storeAvailabilityException'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/availability-exceptions/{id}/update', [AcademyBranchController::class, 'updateAvailabilityException'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/availability-exceptions/{id}/delete', [AcademyBranchController::class, 'deleteAvailabilityException'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/availability-exceptions/{id}/status', [AcademyBranchController::class, 'cycleAvailabilityExceptionStatus'])->middleware(['academy-panel','csrf']);
Router::get('/academy/admin/national-holidays', [NationalHolidayController::class, 'index'])->middleware('academy-panel');
Router::post('/academy/admin/national-holidays', [NationalHolidayController::class, 'store'])->middleware(['site-admin','csrf']);
Router::post('/academy/admin/national-holidays/{id}/update', [NationalHolidayController::class, 'update'])->middleware(['site-admin','csrf']);
Router::post('/academy/admin/national-holidays/{id}/delete', [NationalHolidayController::class, 'delete'])->middleware(['site-admin','csrf']);
Router::post('/academy/admin/national-holidays/{id}/status', [NationalHolidayController::class, 'toggleStatus'])->middleware(['site-admin','csrf']);
Router::post('/academy/admin/national-holiday-settings/{academyId}', [NationalHolidayController::class, 'saveAcademySetting'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/branch-offerings/lessons', [AcademyBranchOfferingController::class, 'storeLesson'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/branch-offerings/lessons/{id}/update', [AcademyBranchOfferingController::class, 'updateLesson'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/branch-offerings/lessons/{id}/status', [AcademyBranchOfferingController::class, 'cycleLessonStatus'])->middleware(['academy-panel','csrf']);
Router::get('/academy/admin/branch-offerings/lessons/realtime-version', [AcademyBranchOfferingController::class, 'lessonsRealtimeVersion'])->middleware('academy-panel');
Router::get('/academy/admin/branch-offerings/schedules/realtime-version', [AcademyBranchOfferingController::class, 'schedulesRealtimeVersion'])->middleware('academy-panel');
Router::post('/academy/admin/branch-offerings/lesson-catalog', [AcademyBranchOfferingController::class, 'storeLessonCatalog'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/branch-offerings/schedules', [AcademyBranchOfferingController::class, 'storeSchedule'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/branch-offerings/schedules/{id}/update', [AcademyBranchOfferingController::class, 'updateSchedule'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/branch-offerings/{type}/{id}/delete', [AcademyBranchOfferingController::class, 'delete'])->middleware(['academy-panel','csrf']);
Router::get('/academy/admin/courses', [AcademyCourseController::class, 'index'])->middleware('academy-panel');
Router::post('/academy/admin/courses', [AcademyCourseController::class, 'store'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/courses/{id}/update', [AcademyCourseController::class, 'update'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/courses/{id}/delete', [AcademyCourseController::class, 'destroy'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/courses/{id}/status', [AcademyCourseController::class, 'cycleStatus'])->middleware(['academy-panel','csrf']);
Router::get('/academy/admin/courses/realtime-version', [AcademyCourseController::class, 'realtimeVersion'])->middleware('academy-panel');
Router::get('/academy/admin/courses/student-options', [AcademyCourseController::class, 'studentOptions'])->middleware('academy-panel');
Router::post('/academy/admin/students', [AcademyCourseController::class, 'storeStudent'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/course-levels', [AcademyCourseController::class, 'storeLevel'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/course-levels/{id}/update', [AcademyCourseController::class, 'updateLevel'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/course-levels/{id}/delete', [AcademyCourseController::class, 'deleteLevel'])->middleware(['academy-panel','csrf']);
Router::get('/academy/admin/terms/realtime-version', [AcademyTermController::class, 'realtimeVersion'])->middleware('academy-panel');
Router::get('/academy/admin/terms', [AcademyTermController::class, 'index'])->middleware('academy-panel');
Router::get('/academy/admin/term-available-times', [AcademyTermAvailabilityController::class, 'index'])->middleware('academy-panel');
Router::get('/academy/admin/term-invoices', [AcademyTermController::class, 'invoices'])->middleware('academy-panel');
Router::post('/academy/admin/term-invoices/{id}/update', [AcademyTermController::class, 'updateInvoice'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/term-invoices/{invoiceId}/installments/{installmentId}/zarinpal', [ZarinpalPaymentController::class, 'start'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/term-invoices/{invoiceId}/installments/{installmentId}/offline', [ZarinpalPaymentController::class, 'offline'])->middleware(['academy-panel','csrf']);
Router::get('/academy/payments/zarinpal/callback', [ZarinpalPaymentController::class, 'callback']);
Router::get('/academy/admin/subscriptions', [AcademySubscriptionController::class, 'index'])->middleware('academy-panel');
Router::post('/academy/admin/subscriptions/{id}/zarinpal', [AcademySubscriptionController::class, 'start'])->middleware(['academy-panel','csrf']);
Router::get('/academy/subscriptions/zarinpal/callback', [AcademySubscriptionController::class, 'callback']);
Router::post('/academy/admin/terms', [AcademyTermController::class, 'store'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/terms/{id}/update', [AcademyTermController::class, 'update'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/terms/{id}/status', [AcademyTermController::class, 'cycleStatus'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/terms/{id}/sessions/{sessionId}/cancel', [AcademyTermController::class, 'cancelSession'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/terms/{id}/sessions/{sessionId}/cancel/approve', [AcademyTermController::class, 'approveSessionCancellation'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/terms/{id}/sessions/{sessionId}/cancel/reject', [AcademyTermController::class, 'rejectSessionCancellation'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/terms/{id}/sessions/{sessionId}/restore', [AcademyTermController::class, 'restoreSession'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/terms/{id}/delete', [AcademyTermController::class, 'destroy'])->middleware(['academy-panel','csrf']);
Router::post('/academy/admin/term-discounts', [AcademyTermController::class, 'storeDiscount'])->middleware(['academy-panel','csrf']);
Router::get('/academy/admin/class-schedules', [AcademyClassScheduleController::class, 'index'])->middleware('academy-panel');
Router::get('/academy/admin/class-schedule-week-bounds', [AcademyWeeklyScheduleBoundsController::class, 'index'])->middleware('academy-panel');
Router::post('/academy/admin/class-schedules/{id}/attendance', [AcademyClassScheduleController::class, 'attendance'])->middleware(['academy-panel','csrf']);

Router::group(
    ['prefix' => '/academy'],
    function () {
        Router::get('/',            [AcademyController::class,'index']);
        Router::get('/create',      [AcademyController::class,'create']);
        Router::post('/',           [AcademyController::class,'store']);
        Router::get('/{id}',        [AcademyController::class,'show']);
        Router::get('/{id}/edit',   [AcademyController::class,'edit']);
        Router::put('/{id}',        [AcademyController::class,'update']);
        Router::delete('/{id}',     [AcademyController::class,'destroy']);
    }


);
