const assert = require('node:assert/strict');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const {chromium} = require(process.env.PLAYWRIGHT_CORE_PATH || '../storage/notation-browser-check/package');
(async()=>{
  const browser = await chromium.launch({channel:'msedge',headless:true});
  try {
    for (const locale of ['fa','en']) {
      const page = await browser.newPage({viewport:{width:360,height:780}});
      const errors=[]; page.on('pageerror',e=>errors.push(e.message));
      page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
      await page.addInitScript(({locale})=>{
        window.NOTATION_BOOT={locale,userId:1,embedded:true};
        window.lastRoute={};
        window.SornazNotation={postMessage(raw){const d=JSON.parse(raw);if(d.action==='route'){window.lastRoute=d;return;}window.lastRequest=d;
          queueMicrotask(()=>{let data=true;
            if(d.action==='list')data={items:window.mockSheet?[{...window.mockSheet,title:window.mockSheet.metadata.title}]:[],has_more:false};
            if(d.action==='get')data=window.mockSheet;
            if(d.action==='instruments')data=[{id:7,fa:'پیانو',en:'Piano'},{id:42,fa:'سنتور',en:'Santur'}];
            if(d.action==='save'){window.savedPayload=d.payload;data=window.mockSheet={...d.payload,id:1,version:(window.mockSheet?.version||0)+1,editable:true};}
            window.Notation.receive(d.id,data,null);
          });
        }};
      },{locale});
      await page.goto(pathToFileURL(path.resolve('assets/notation/index.html')).href);
      await page.locator('[data-action=new]').click();
      await page.locator('[name=title]').fill('Score test');
      assert.equal(await page.locator('[name=tempo_text]').isDisabled(),true);
      assert.equal(await page.locator('[name=public]').count(),0);
      assert.equal(await page.locator('[name=title]').getAttribute('placeholder'),null);
      await page.locator('[name=instrument]').selectOption('42');
      await page.locator('.beat-picker summary').click();
      await page.locator('[data-action=beat-unit][data-value=q]').click();
      assert.equal(await page.locator('[name=tempo_text]').isDisabled(),true);
      await page.locator('[name=bpm]').fill('12.3abc-');
      assert.equal(await page.locator('[name=bpm]').inputValue(),'12');
      await page.locator('[name=bpm]').fill('100');
      assert.equal(await page.locator('[name=clef] option').count(),7);
      assert.deepEqual(await page.locator('[name=tempo_text] option').evaluateAll(es=>es.map(e=>e.value)),['','Andante','Andantino','Andante moderato']);
      await page.locator('[name=tempo_text]').selectOption('Andante');
      await page.locator('[name=bpm]').fill('180');
      assert.equal(await page.locator('[name=tempo_text]').inputValue(),'');
      assert.deepEqual(await page.locator('[name=tempo_text] option').evaluateAll(es=>es.map(e=>e.value)),['','Presto']);
      await page.locator('[name=bpm]').fill('100');
      await page.locator('[name=tempo_text]').selectOption('Andante');
      assert.equal(await page.locator('[name=copyright]').count(),0);
      assert.deepEqual(await page.locator('[name=tempo_note] option').evaluateAll(es=>es.map(e=>e.value)),['','w','h','q','8','16','32','64']);
      await page.locator('[name=lyricist]').fill('Lyric writer');
      await page.locator('[name=composer]').fill('Composer name');
      await page.locator('[name=clef]').selectOption('alto');
      await page.screenshot({path:`storage/notation-browser-check/form-${locale}.png`});
      const rows=await page.locator('.form-row').evaluateAll(es=>es.map(e=>({top:e.getBoundingClientRect().top,bottom:e.getBoundingClientRect().bottom})));
      const gaps=rows.slice(1).map((r,i)=>r.top-rows[i].bottom);assert.ok(Math.max(...gaps)-Math.min(...gaps)<2);
      await page.locator('[type=submit]').click();
      assert.equal(await page.locator('.state.unsaved').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(254, 240, 138)');
      assert.equal(await page.locator('.piano .white').count(),52);
      assert.equal(await page.locator('.piano .black').count(),36);
      assert.equal(await page.locator('.editor-footer [data-action=save]').count(),0);
      assert.equal(await page.locator('.editor-header [data-action=save]').count(),1);
      assert.equal(await page.locator('.editor-header [data-action=pdf],.editor-header [data-action=export]').count(),0);
      assert.equal(await page.locator('.duration-choice .duration-btn').count(),7);
      assert.equal(await page.locator('.duration-btn svg').count(),7);
      assert.deepEqual(await page.locator('.rest-key').evaluate(e=>[e.offsetWidth,e.offsetHeight]),await page.locator('.palette-key').evaluate(e=>[e.offsetWidth,e.offsetHeight]));
      assert.equal(await page.locator('.duration-choice .dot-btn').count(),2);
      assert.equal(await page.locator('.duration-choice .duration-btn[aria-pressed=true]').getAttribute('data-value'),'q');
      assert.equal(await page.locator('.tempo').textContent().then(t=>t.includes('4/4')),false);
      await page.locator('.dot-btn[data-value="1"]').click();
      assert.equal(await page.locator('.dot-btn[aria-pressed=true]').getAttribute('data-value'),'1');
      await page.locator('.dot-btn[data-value="2"]').click();
      assert.equal(await page.locator('.dot-btn[aria-pressed=true]').count(),1);
      await page.locator('.dot-btn[data-value="2"]').click();
      assert.equal(await page.locator('.dot-btn[aria-pressed=true]').count(),0);
      assert.equal(await page.locator('.palette').getAttribute('aria-hidden'),'true');
      assert.ok((await page.locator('.credits').textContent()).indexOf('Lyric writer')<(await page.locator('.credits').textContent()).indexOf('Composer name'));
      await page.locator('.palette-key').click();
      await page.waitForTimeout(250);
      assert.equal(await page.locator('.palette').getAttribute('aria-hidden'),'false');
      assert.deepEqual(await page.locator('.palette select').evaluateAll(es=>es.map(e=>e.selectedOptions[0].textContent)),['','','','','','']);
      assert.ok(await page.locator('.palette').evaluate(e=>Math.abs(e.getBoundingClientRect().bottom-innerHeight)<2));
      await page.screenshot({path:`storage/notation-browser-check/tools-${locale}.png`});
      await page.locator('.palette-heading button').click();
      await page.evaluate(()=>Notation.configure({nativeToolbar:true}));
      await page.locator('.duration-btn[data-value="8"]').click();
      for(let i=0;i<10;i++) await page.locator('.white[data-pitch=C4]').click();
      await page.locator('.duration-btn[data-value="w"]').click();
      await page.locator('.white[data-pitch=C4]').click();
      await page.evaluate(()=>Notation.command('save'));
      const labels = await page.locator('dialog button').allTextContents();
      assert.deepEqual(labels,locale==='fa'?['خیر','بلی']:['No','Yes']);
      await page.locator('[data-action=yes]').click();
      await page.waitForFunction(()=>!!window.savedPayload);
      assert.equal(await page.locator('.state.synced').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(187, 247, 208)');
      assert.equal(await page.evaluate(()=>window.savedPayload.metadata.instrument),'42');
      const measures=await page.evaluate(()=>window.savedPayload.score.measures);
      assert.ok(measures.some(b=>b.notes.some(n=>n.tieNext)));
      assert.ok(measures.at(-1).notes.length,'saved scores have no trailing empty measures');
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
      assert.equal(await page.evaluate(()=>document.querySelector('#score').scrollWidth<=document.querySelector('#score').clientWidth),true);
      await page.locator('[data-bar="1"][data-note="1"]').click();
      await page.evaluate(()=>Notation.command('play'));
      await page.waitForTimeout(180);
      assert.equal(await page.evaluate(()=>document.querySelector('[data-bar="1"]').closest('svg').querySelectorAll('[fill="#0065ff"]').length>0),true);
      await page.evaluate(()=>Notation.command('play'));
      await page.locator('[data-bar="0"][data-note="0"]').click();
      const noteCount=await page.locator('[data-note]').count();
      assert.equal(await page.locator('.score-delete svg').count(),1);
      assert.equal(await page.locator('.score-delete').evaluate(e=>getComputedStyle(e).color),'rgb(220, 38, 38)');
      await page.locator('[data-action=delete-note]').click();
      assert.equal(await page.locator('[data-note]').count(),noteCount-1);
      await page.locator('[data-action=undo]').click();
      assert.equal(await page.locator('[data-note]').count(),noteCount);
      await page.locator('[data-action=redo]').click();
      assert.equal(await page.locator('[data-note]').count(),noteCount-1);
      await page.evaluate(()=>Notation.command('export'));
      await page.waitForFunction(()=>window.lastRequest.action==='export');
      await page.evaluate(()=>Notation.command('pdf'));
      await page.waitForFunction(()=>window.lastRequest.action==='pdf');
      assert.ok((await page.evaluate(()=>window.lastRequest.html)).includes('print-page'));
      await page.evaluate(()=>Notation.command('metadata'));
      assert.equal(await page.locator('[name=title]').inputValue(),'Score test');
      await page.locator('[type=submit]').click();
      await page.evaluate(()=>Notation.command('save'));
      await page.locator('[data-action=yes]').click();
      await page.waitForFunction(()=>window.lastRoute.dirty===false);
      await page.evaluate(()=>Notation.command('back'));
      await page.locator('[data-action=visibility]').waitFor();
      const beforeVisibility=await page.evaluate(()=>window.mockSheet.visibility);
      await page.locator('[data-action=visibility]').click();
      await page.waitForFunction(before=>window.mockSheet.visibility!==before,beforeVisibility);
      await page.locator('[data-action=pdf-item]').click();
      await page.waitForFunction(()=>window.lastRequest.action==='pdf');
      await page.locator('[data-action=open]').click();
      await page.screenshot({path:`storage/notation-browser-check/revision-${locale}.png`});
      assert.deepEqual(errors,[]);
      await page.evaluate(()=>{window.Notation.configure({userId:0});});
      assert.equal(await page.locator('.editor-header [data-action=export]').count(),0);
      assert.equal(await page.locator('.editor-footer').count(),0);
      assert.equal(await page.locator('.editor-actions button').count(),1);

      const ottavas=await page.evaluate(()=>{
        const s=NotationModel.fresh();s.score.measures=['A0','B1','C2','G2','A2','C7','B7','C8'].map(pitch=>({notes:[{pitch,duration:'q',dots:0,rest:false}]}));
        const original=JSON.stringify(s),target=document.createElement('div');target.style.width='340px';document.body.append(target);NotationRenderer.draw(target,s);
        const labels=[...target.querySelectorAll('.ottava-label')].map(e=>e.textContent);
        const fits=[...target.querySelectorAll('svg')].every(svg=>{const box=svg.getBBox(),view=svg.viewBox.baseVal;return box.y>=view.y-1&&box.y+box.height<=view.y+view.height+1;});
        const paper=NotationRenderer.printDocument(s,'en');target.remove();return {labels,fits,unchanged:JSON.stringify(s)===original,paper};
      });
      for(const label of ['16vb','8vb','8va','16va']){assert.ok(ottavas.labels.includes(label),label);assert.ok(ottavas.paper.includes('>'+label+'</text>'));}
      assert.equal(ottavas.fits,true);assert.equal(ottavas.unchanged,true);
      const printHtml=await page.evaluate(()=>{
        const s=NotationModel.fresh();s.metadata.title='A4 pagination';s.metadata.composer='علی حیدری';s.metadata.arranger='یاسین موسوی';
        s.score.measures=Array.from({length:64},()=>({notes:Array.from({length:16},()=>({pitch:'C4',duration:'16',dots:0,rest:false}))}));
        return NotationRenderer.printDocument(s,'fa',{q:'♩'});
      });
      const paper=await browser.newPage();await paper.setContent(printHtml);
      assert.equal(await paper.locator('.print-page').count(),2);
      assert.equal(await paper.locator('.print-page').first().locator('.print-staff').count(),10);
      assert.equal(await paper.locator('.print-page').nth(1).locator('.print-staff').count(),3);
      const pdf=await paper.pdf({path:`storage/notation-browser-check/a4-${locale}.pdf`,preferCSSPageSize:true,printBackground:true});
      assert.equal(pdf.subarray(0,4).toString(),'%PDF');await paper.close();
      await page.close();
    }
    console.log('Notation browser: fa/en mobile toolbar, keyboard, input, clefs, ties and playback passed.');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});

